// Cosmic horror: 1920s investigation and forbidden lore — Sites, Clues, Leads.
const cosmicHorrorVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Cosmic Horror',
    'hint': '1920s dread and forbidden lore: Sites, Clues, Leads',
    'k.character': 'Person of Interest',
    'kp.character': 'Persons of Interest',
    'k.location': 'Site',
    'kp.location': 'Sites',
    'k.item': 'Artifact',
    'kp.item': 'Artifacts & Evidence',
    'k.creature': 'Mythos Being',
    'kp.creature': 'Mythos Bestiary',
    'k.faction': 'Organization',
    'kp.faction': 'Organizations',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Aeon',
    'kp.era': 'Aeons',
    'k.religion': 'Cult',
    'kp.religion': 'Cults',
    'k.magicSystem': 'Occult Art',
    'kp.magicSystem': 'Occult Arts',
    'k.technology': 'Apparatus',
    'kp.technology': 'Apparatus',
    'k.concept': 'Clue',
    'kp.concept': 'Clue Board',
    'k.loreDocument': 'Case File',
    'kp.loreDocument': 'Case Files',
    'k.campaign': 'Casebook',
    'kp.campaign': 'Casebooks',
    'k.quest': 'Lead',
    'kp.quest': 'Leads',
    'k.session': 'Chapter',
    'kp.session': 'Chapters',
    't:Spell': 'Ritual',
    't:Spells': 'Rituals',
    't:School': 'Tome of Origin',
    't:Casting Time': 'Ritual Time',
    't:Components': 'Ingredients',
    't:Legendary Actions': 'Unspeakable Actions',
    't:Class / Profession': 'Occupation',
    't:Magic Items': 'Occult Artifacts',
    't:Deities': 'Entities',
    't:Deity': 'Entity',
    't:Challenge Rating': 'Threat Level',
    't:Source of Power': 'Forbidden Source',
    't:Rules & Limits': 'Costs & Perils',
    't:Quest Giver': 'Client',
    't:Headquarters': 'Lodge',
  },
  'ru': {
    'name': 'Космический ужас',
    'hint': 'Страх 1920-х и запретные знания: Места, Улики, Зацепки',
    'k.character': 'Фигурант',
    'kp.character': 'Фигуранты',
    'k.location': 'Место',
    'kp.location': 'Места',
    'k.item': 'Артефакт',
    'kp.item': 'Артефакты и улики',
    'k.creature': 'Существо Мифа',
    'kp.creature': 'Бестиарий Мифа',
    'k.faction': 'Организация',
    'kp.faction': 'Организации',
    'k.event': 'Происшествие',
    'kp.event': 'Происшествия',
    'k.era': 'Эон',
    'kp.era': 'Эоны',
    'k.religion': 'Культ',
    'kp.religion': 'Культы',
    'k.magicSystem': 'Оккультное искусство',
    'kp.magicSystem': 'Оккультные искусства',
    'k.technology': 'Аппарат',
    'kp.technology': 'Аппаратура',
    'k.concept': 'Улика',
    'kp.concept': 'Доска улик',
    'k.loreDocument': 'Досье',
    'kp.loreDocument': 'Досье',
    'k.campaign': 'Расследование',
    'kp.campaign': 'Расследования',
    'k.quest': 'Зацепка',
    'kp.quest': 'Зацепки',
    'k.session': 'Глава',
    'kp.session': 'Главы',
    't:Spell': 'Ритуал',
    't:Spells': 'Ритуалы',
    't:School': 'Том-источник',
    't:Casting Time': 'Время ритуала',
    't:Components': 'Ингредиенты',
    't:Legendary Actions': 'Неописуемые действия',
    't:Class / Profession': 'Род занятий',
    't:Magic Items': 'Оккультные артефакты',
    't:Deities': 'Сущности',
    't:Deity': 'Сущность',
    't:Challenge Rating': 'Уровень угрозы',
    't:Source of Power': 'Запретный источник',
    't:Rules & Limits': 'Цена и опасности',
    't:Quest Giver': 'Клиент',
    't:Headquarters': 'Ложа',
  },
  'de': {
    'name': 'Kosmischer Horror',
    'hint': 'Grauen der 1920er, verbotenes Wissen: Schauplätze, Hinweise, Spuren',
    'k.character': 'Person von Interesse',
    'kp.character': 'Personen von Interesse',
    'k.location': 'Schauplatz',
    'kp.location': 'Schauplätze',
    'k.item': 'Artefakt',
    'kp.item': 'Artefakte & Beweise',
    'k.creature': 'Mythoswesen',
    'kp.creature': 'Mythos-Bestiarium',
    'k.faction': 'Organisation',
    'kp.faction': 'Organisationen',
    'k.event': 'Vorfall',
    'kp.event': 'Vorfälle',
    'k.era': 'Äon',
    'kp.era': 'Äonen',
    'k.religion': 'Kult',
    'kp.religion': 'Kulte',
    'k.magicSystem': 'Okkulte Kunst',
    'kp.magicSystem': 'Okkulte Künste',
    'k.technology': 'Apparat',
    'kp.technology': 'Apparaturen',
    'k.concept': 'Hinweis',
    'kp.concept': 'Pinnwand',
    'k.loreDocument': 'Fallakte',
    'kp.loreDocument': 'Fallakten',
    'k.campaign': 'Ermittlung',
    'kp.campaign': 'Ermittlungen',
    'k.quest': 'Spur',
    'kp.quest': 'Spuren',
    'k.session': 'Kapitel',
    'kp.session': 'Kapitel',
    't:Spell': 'Ritual',
    't:Spells': 'Rituale',
    't:School': 'Ursprungsschrift',
    't:Casting Time': 'Ritualdauer',
    't:Components': 'Zutaten',
    't:Legendary Actions': 'Unsägliche Aktionen',
    't:Class / Profession': 'Beruf',
    't:Magic Items': 'Okkulte Artefakte',
    't:Deities': 'Wesenheiten',
    't:Deity': 'Wesenheit',
    't:Challenge Rating': 'Bedrohungsgrad',
    't:Source of Power': 'Verbotene Quelle',
    't:Rules & Limits': 'Preis & Gefahren',
    't:Quest Giver': 'Auftraggeber',
    't:Headquarters': 'Loge',
  },
  'fr': {
    'name': 'Horreur cosmique',
    'hint': 'Effroi des années 1920 et savoir interdit : Sites, Indices, Pistes',
    'k.character': 'Personne d\'intérêt',
    'kp.character': 'Personnes d\'intérêt',
    'k.location': 'Site',
    'kp.location': 'Sites',
    'k.item': 'Artefact',
    'kp.item': 'Artefacts et preuves',
    'k.creature': 'Entité du Mythe',
    'kp.creature': 'Bestiaire du Mythe',
    'k.faction': 'Organisation',
    'kp.faction': 'Organisations',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Éon',
    'kp.era': 'Éons',
    'k.religion': 'Culte',
    'kp.religion': 'Cultes',
    'k.magicSystem': 'Art occulte',
    'kp.magicSystem': 'Arts occultes',
    'k.technology': 'Appareil',
    'kp.technology': 'Appareils',
    'k.concept': 'Indice',
    'kp.concept': 'Tableau des indices',
    'k.loreDocument': 'Dossier',
    'kp.loreDocument': 'Dossiers',
    'k.campaign': 'Enquête',
    'kp.campaign': 'Enquêtes',
    'k.quest': 'Piste',
    'kp.quest': 'Pistes',
    'k.session': 'Chapitre',
    'kp.session': 'Chapitres',
    't:Spell': 'Rituel',
    't:Spells': 'Rituels',
    't:School': 'Grimoire d\'origine',
    't:Casting Time': 'Durée du rituel',
    't:Components': 'Ingrédients',
    't:Legendary Actions': 'Actions indicibles',
    't:Class / Profession': 'Métier',
    't:Magic Items': 'Artefacts occultes',
    't:Deities': 'Entités',
    't:Deity': 'Entité',
    't:Challenge Rating': 'Niveau de menace',
    't:Source of Power': 'Source interdite',
    't:Rules & Limits': 'Prix et périls',
    't:Quest Giver': 'Commanditaire',
    't:Headquarters': 'Loge',
  },
  'zh': {
    'name': '宇宙恐怖',
    'hint': '1920年代的恐惧与禁忌知识：地点、线索、追查',
    'k.character': '相关人物',
    'kp.character': '相关人物',
    'k.location': '地点',
    'kp.location': '地点',
    'k.item': '文物',
    'kp.item': '文物与证物',
    'k.creature': '神话生物',
    'kp.creature': '神话图鉴',
    'k.faction': '组织',
    'kp.faction': '组织',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '纪元',
    'kp.era': '纪元',
    'k.religion': '邪教',
    'kp.religion': '邪教',
    'k.magicSystem': '秘术',
    'kp.magicSystem': '秘术',
    'k.technology': '装置',
    'kp.technology': '装置',
    'k.concept': '线索',
    'kp.concept': '线索板',
    'k.loreDocument': '案卷',
    'kp.loreDocument': '案卷',
    'k.campaign': '案件簿',
    'kp.campaign': '案件簿',
    'k.quest': '追查',
    'kp.quest': '追查',
    'k.session': '章节',
    'kp.session': '章节',
    't:Spell': '仪式',
    't:Spells': '仪式',
    't:School': '出处典籍',
    't:Casting Time': '仪式时间',
    't:Components': '材料',
    't:Legendary Actions': '不可名状动作',
    't:Class / Profession': '职业',
    't:Magic Items': '神秘物品',
    't:Deities': '古老存在',
    't:Deity': '古老存在',
    't:Challenge Rating': '威胁等级',
    't:Source of Power': '禁忌之源',
    't:Rules & Limits': '代价与风险',
    't:Quest Giver': '委托人',
    't:Headquarters': '会所',
  },
};
