// Cyberpunk: neon chrome and street slang — Runners, Sectors, Gigs.
const cyberpunkVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Cyberpunk',
    'hint': 'Neon chrome and street slang: Runners, Sectors, Gigs',
    'k.character': 'Runner',
    'kp.character': 'Runners',
    'k.location': 'Sector',
    'kp.location': 'Sectors',
    'k.item': 'Gear',
    'kp.item': 'Gear & Tech',
    'k.creature': 'Cyberform',
    'kp.creature': 'Cyberforms',
    'k.faction': 'Syndicate',
    'kp.faction': 'Corps & Gangs',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Epoch',
    'kp.era': 'Epochs',
    'k.religion': 'Cult',
    'kp.religion': 'Cults',
    'k.magicSystem': 'Protocol',
    'kp.magicSystem': 'Protocols',
    'k.technology': 'Cyberware',
    'kp.technology': 'Cyberware',
    'k.concept': 'Data Fragment',
    'kp.concept': 'Data Vault',
    'k.loreDocument': 'Data Shard',
    'kp.loreDocument': 'Data Shards',
    'k.campaign': 'Operation',
    'kp.campaign': 'Operations',
    'k.quest': 'Gig',
    'kp.quest': 'Gigs',
    'k.session': 'Run',
    'kp.session': 'Runs',
    't:Spell': 'Protocol',
    't:School': 'Subsystem',
    't:Casting Time': 'Activation Time',
    't:Components': 'Requirements',
    't:Legendary Actions': 'Overdrive Actions',
  },
  'ru': {
    'name': 'Киберпанк',
    'hint': 'Неон, хром и уличный сленг: Раннеры, Сектора, Заказы',
    'k.character': 'Раннер',
    'kp.character': 'Раннеры',
    'k.location': 'Сектор',
    'kp.location': 'Сектора',
    'k.item': 'Снаряжение',
    'kp.item': 'Снаряжение и тех',
    'k.creature': 'Киберформа',
    'kp.creature': 'Киберформы',
    'k.faction': 'Синдикат',
    'kp.faction': 'Корпорации и банды',
    'k.event': 'Инцидент',
    'kp.event': 'Инциденты',
    'k.era': 'Эпоха',
    'kp.era': 'Эпохи',
    'k.religion': 'Культ',
    'kp.religion': 'Культы',
    'k.magicSystem': 'Протокол',
    'kp.magicSystem': 'Протоколы',
    'k.technology': 'Кибервэр',
    'kp.technology': 'Кибервэр',
    'k.concept': 'Фрагмент данных',
    'kp.concept': 'Хранилище данных',
    'k.loreDocument': 'Дата-шард',
    'kp.loreDocument': 'Дата-шарды',
    'k.campaign': 'Операция',
    'kp.campaign': 'Операции',
    'k.quest': 'Заказ',
    'kp.quest': 'Заказы',
    'k.session': 'Забег',
    'kp.session': 'Забеги',
    't:Spell': 'Протокол',
    't:School': 'Подсистема',
    't:Casting Time': 'Время активации',
    't:Components': 'Требования',
    't:Legendary Actions': 'Действия овердрайва',
  },
  'de': {
    'name': 'Cyberpunk',
    'hint': 'Neon, Chrom und Straßenslang: Runner, Sektoren, Gigs',
    'k.character': 'Runner',
    'kp.character': 'Runner',
    'k.location': 'Sektor',
    'kp.location': 'Sektoren',
    'k.item': 'Ausrüstung',
    'kp.item': 'Ausrüstung & Tech',
    'k.creature': 'Cyberform',
    'kp.creature': 'Cyberformen',
    'k.faction': 'Syndikat',
    'kp.faction': 'Konzerne & Gangs',
    'k.event': 'Zwischenfall',
    'kp.event': 'Zwischenfälle',
    'k.era': 'Epoche',
    'kp.era': 'Epochen',
    'k.religion': 'Kult',
    'kp.religion': 'Kulte',
    'k.magicSystem': 'Protokoll',
    'kp.magicSystem': 'Protokolle',
    'k.technology': 'Cyberware',
    'kp.technology': 'Cyberware',
    'k.concept': 'Datenfragment',
    'kp.concept': 'Datentresor',
    'k.loreDocument': 'Daten-Splitter',
    'kp.loreDocument': 'Daten-Splitter',
    'k.campaign': 'Operation',
    'kp.campaign': 'Operationen',
    'k.quest': 'Gig',
    'kp.quest': 'Gigs',
    'k.session': 'Run',
    'kp.session': 'Runs',
    't:Spell': 'Protokoll',
    't:School': 'Subsystem',
    't:Casting Time': 'Aktivierungszeit',
    't:Components': 'Anforderungen',
    't:Legendary Actions': 'Overdrive-Aktionen',
  },
  'fr': {
    'name': 'Cyberpunk',
    'hint': 'Chrome néon et argot des rues : Runners, Secteurs, Contrats',
    'k.character': 'Runner',
    'kp.character': 'Runners',
    'k.location': 'Secteur',
    'kp.location': 'Secteurs',
    'k.item': 'Équipement',
    'kp.item': 'Équipement et tech',
    'k.creature': 'Cyberforme',
    'kp.creature': 'Cyberformes',
    'k.faction': 'Syndicat',
    'kp.faction': 'Corpos et gangs',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Époque',
    'kp.era': 'Époques',
    'k.religion': 'Culte',
    'kp.religion': 'Cultes',
    'k.magicSystem': 'Protocole',
    'kp.magicSystem': 'Protocoles',
    'k.technology': 'Cyberware',
    'kp.technology': 'Cyberware',
    'k.concept': 'Fragment de données',
    'kp.concept': 'Coffre de données',
    'k.loreDocument': 'Éclat de données',
    'kp.loreDocument': 'Éclats de données',
    'k.campaign': 'Opération',
    'kp.campaign': 'Opérations',
    'k.quest': 'Contrat',
    'kp.quest': 'Contrats',
    'k.session': 'Run',
    'kp.session': 'Runs',
    't:Spell': 'Protocole',
    't:School': 'Sous-système',
    't:Casting Time': 'Temps d\'activation',
    't:Components': 'Prérequis',
    't:Legendary Actions': 'Actions overdrive',
  },
  'zh': {
    'name': '赛博朋克',
    'hint': '霓虹铬光与街头黑话：狂奔者、区块、委托',
    'k.character': '狂奔者',
    'kp.character': '狂奔者',
    'k.location': '区块',
    'kp.location': '区块',
    'k.item': '装备',
    'kp.item': '装备与科技',
    'k.creature': '赛博生物',
    'kp.creature': '赛博生物',
    'k.faction': '辛迪加',
    'kp.faction': '公司与帮派',
    'k.event': '突发事件',
    'kp.event': '突发事件',
    'k.era': '时代',
    'kp.era': '时代',
    'k.religion': '教派',
    'kp.religion': '教派',
    'k.magicSystem': '协议',
    'kp.magicSystem': '协议',
    'k.technology': '义体',
    'kp.technology': '义体',
    'k.concept': '数据碎片',
    'kp.concept': '数据保险库',
    'k.loreDocument': '数据芯片',
    'kp.loreDocument': '数据芯片',
    'k.campaign': '行动',
    'kp.campaign': '行动',
    'k.quest': '委托',
    'kp.quest': '委托',
    'k.session': '狂奔',
    'kp.session': '狂奔',
    't:Spell': '协议',
    't:School': '子系统',
    't:Casting Time': '激活时间',
    't:Components': '要求',
    't:Legendary Actions': '超频动作',
  },
};
