// Gothic horror: candlelit decay and dread — Souls, Haunts, Hunts.
const gothicHorrorVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Gothic Horror',
    'hint': 'Candlelit decay and dread: Souls, Haunts, Hunts',
    'k.character': 'Soul',
    'kp.character': 'Dramatis Personae',
    'k.location': 'Haunt',
    'kp.location': 'Haunts',
    'k.item': 'Relic',
    'kp.item': 'Relics & Curios',
    'k.creature': 'Horror',
    'kp.creature': 'Horrors',
    'k.faction': 'House',
    'kp.faction': 'Houses & Orders',
    'k.event': 'Tragedy',
    'kp.event': 'Tragedies',
    'k.era': 'Age',
    'kp.era': 'Ages',
    'k.religion': 'Faith',
    'kp.religion': 'Faiths',
    'k.magicSystem': 'Dark Art',
    'kp.magicSystem': 'Dark Arts',
    'k.technology': 'Invention',
    'kp.technology': 'Inventions',
    'k.concept': 'Mystery',
    'kp.concept': 'Mysteries',
    'k.loreDocument': 'Manuscript',
    'kp.loreDocument': 'Manuscripts',
    'k.campaign': 'Chronicle',
    'kp.campaign': 'Chronicles',
    'k.quest': 'Hunt',
    'kp.quest': 'Hunts',
    'k.session': 'Night',
    'kp.session': 'Nights',
    't:Spell': 'Rite',
    't:Spells': 'Rites',
    't:School': 'Tradition',
    't:Casting Time': 'Invocation Time',
    't:Components': 'Offerings',
    't:Legendary Actions': 'Dread Actions',
    't:Magic Items': 'Cursed Relics',
    't:Source of Power': 'Dark Pact',
    't:Rules & Limits': 'Price & Taboos',
    't:Challenge Rating': 'Dread Rating',
    't:Race / Ancestry': 'Bloodline',
    't:Headquarters': 'Seat',
    't:Habitat': 'Haunting Grounds',
    't:Quest Giver': 'Petitioner',
  },
  'ru': {
    'name': 'Готический ужас',
    'hint': 'Свечи, тлен и страх: Души, Проклятые места, Охоты',
    'k.character': 'Душа',
    'kp.character': 'Действующие лица',
    'k.location': 'Проклятое место',
    'kp.location': 'Проклятые места',
    'k.item': 'Реликвия',
    'kp.item': 'Реликвии и диковины',
    'k.creature': 'Чудовище',
    'kp.creature': 'Чудовища',
    'k.faction': 'Дом',
    'kp.faction': 'Дома и ордены',
    'k.event': 'Трагедия',
    'kp.event': 'Трагедии',
    'k.era': 'Век',
    'kp.era': 'Века',
    'k.religion': 'Вера',
    'kp.religion': 'Верования',
    'k.magicSystem': 'Тёмное искусство',
    'kp.magicSystem': 'Тёмные искусства',
    'k.technology': 'Изобретение',
    'kp.technology': 'Изобретения',
    'k.concept': 'Тайна',
    'kp.concept': 'Тайны',
    'k.loreDocument': 'Рукопись',
    'kp.loreDocument': 'Рукописи',
    'k.campaign': 'Хроника',
    'kp.campaign': 'Хроники',
    'k.quest': 'Охота',
    'kp.quest': 'Охоты',
    'k.session': 'Ночь',
    'kp.session': 'Ночи',
    't:Spell': 'Обряд',
    't:Spells': 'Обряды',
    't:School': 'Традиция',
    't:Casting Time': 'Время обряда',
    't:Components': 'Подношения',
    't:Legendary Actions': 'Жуткие действия',
    't:Magic Items': 'Проклятые реликвии',
    't:Source of Power': 'Тёмный договор',
    't:Rules & Limits': 'Цена и запреты',
    't:Challenge Rating': 'Уровень угрозы',
    't:Race / Ancestry': 'Родословная',
    't:Headquarters': 'Резиденция',
    't:Habitat': 'Обиталище',
    't:Quest Giver': 'Проситель',
  },
  'de': {
    'name': 'Gothic Horror',
    'hint': 'Kerzenlicht, Verfall und Grauen: Seelen, Spukorte, Jagden',
    'k.character': 'Seele',
    'kp.character': 'Dramatis Personae',
    'k.location': 'Spukort',
    'kp.location': 'Spukorte',
    'k.item': 'Reliquie',
    'kp.item': 'Reliquien & Kuriosa',
    'k.creature': 'Schreckgestalt',
    'kp.creature': 'Schreckgestalten',
    'k.faction': 'Haus',
    'kp.faction': 'Häuser & Orden',
    'k.event': 'Tragödie',
    'kp.event': 'Tragödien',
    'k.era': 'Zeitalter',
    'kp.era': 'Zeitalter',
    'k.religion': 'Glaube',
    'kp.religion': 'Glaubensrichtungen',
    'k.magicSystem': 'Dunkle Kunst',
    'kp.magicSystem': 'Dunkle Künste',
    'k.technology': 'Erfindung',
    'kp.technology': 'Erfindungen',
    'k.concept': 'Mysterium',
    'kp.concept': 'Mysterien',
    'k.loreDocument': 'Manuskript',
    'kp.loreDocument': 'Manuskripte',
    'k.campaign': 'Chronik',
    'kp.campaign': 'Chroniken',
    'k.quest': 'Jagd',
    'kp.quest': 'Jagden',
    'k.session': 'Nacht',
    'kp.session': 'Nächte',
    't:Spell': 'Ritus',
    't:Spells': 'Riten',
    't:School': 'Tradition',
    't:Casting Time': 'Ritualdauer',
    't:Components': 'Opfergaben',
    't:Legendary Actions': 'Schreckensaktionen',
    't:Magic Items': 'Verfluchte Reliquien',
    't:Source of Power': 'Dunkler Pakt',
    't:Rules & Limits': 'Preis & Tabus',
    't:Challenge Rating': 'Schreckensgrad',
    't:Race / Ancestry': 'Blutlinie',
    't:Headquarters': 'Stammsitz',
    't:Habitat': 'Spukgebiet',
    't:Quest Giver': 'Bittsteller',
  },
  'fr': {
    'name': 'Horreur gothique',
    'hint': 'Bougies, décrépitude et effroi : Âmes, Lieux hantés, Traques',
    'k.character': 'Âme',
    'kp.character': 'Dramatis personae',
    'k.location': 'Lieu hanté',
    'kp.location': 'Lieux hantés',
    'k.item': 'Relique',
    'kp.item': 'Reliques et curiosités',
    'k.creature': 'Horreur',
    'kp.creature': 'Horreurs',
    'k.faction': 'Maison',
    'kp.faction': 'Maisons et ordres',
    'k.event': 'Tragédie',
    'kp.event': 'Tragédies',
    'k.era': 'Âge',
    'kp.era': 'Âges',
    'k.religion': 'Croyance',
    'kp.religion': 'Croyances',
    'k.magicSystem': 'Art ténébreux',
    'kp.magicSystem': 'Arts ténébreux',
    'k.technology': 'Invention',
    'kp.technology': 'Inventions',
    'k.concept': 'Mystère',
    'kp.concept': 'Mystères',
    'k.loreDocument': 'Manuscrit',
    'kp.loreDocument': 'Manuscrits',
    'k.campaign': 'Chronique',
    'kp.campaign': 'Chroniques',
    'k.quest': 'Traque',
    'kp.quest': 'Traques',
    'k.session': 'Nuit',
    'kp.session': 'Nuits',
    't:Spell': 'Rite',
    't:Spells': 'Rites',
    't:School': 'Tradition',
    't:Casting Time': 'Durée du rite',
    't:Components': 'Offrandes',
    't:Legendary Actions': 'Actions d\'effroi',
    't:Magic Items': 'Reliques maudites',
    't:Source of Power': 'Pacte ténébreux',
    't:Rules & Limits': 'Prix et tabous',
    't:Challenge Rating': 'Degré d\'effroi',
    't:Race / Ancestry': 'Lignée',
    't:Headquarters': 'Siège',
    't:Habitat': 'Terrain de chasse',
    't:Quest Giver': 'Commanditaire',
  },
  'zh': {
    'name': '哥特恐怖',
    'hint': '烛光、腐朽与恐惧：灵魂、凶地、狩猎',
    'k.character': '灵魂',
    'kp.character': '登场人物',
    'k.location': '凶地',
    'kp.location': '凶地',
    'k.item': '遗物',
    'kp.item': '遗物与珍玩',
    'k.creature': '魔物',
    'kp.creature': '魔物',
    'k.faction': '家族',
    'kp.faction': '家族与教团',
    'k.event': '悲剧',
    'kp.event': '悲剧',
    'k.era': '时代',
    'kp.era': '时代',
    'k.religion': '信仰',
    'kp.religion': '信仰',
    'k.magicSystem': '黑暗秘术',
    'kp.magicSystem': '黑暗秘术',
    'k.technology': '发明',
    'kp.technology': '发明',
    'k.concept': '谜团',
    'kp.concept': '谜团',
    'k.loreDocument': '手稿',
    'kp.loreDocument': '手稿',
    'k.campaign': '编年史',
    'kp.campaign': '编年史',
    'k.quest': '狩猎',
    'kp.quest': '狩猎',
    'k.session': '夜晚',
    'kp.session': '夜晚',
    't:Spell': '仪式',
    't:Spells': '仪式',
    't:School': '传承',
    't:Casting Time': '仪式时间',
    't:Components': '祭品',
    't:Legendary Actions': '恐惧动作',
    't:Magic Items': '诅咒遗物',
    't:Source of Power': '黑暗契约',
    't:Rules & Limits': '代价与禁忌',
    't:Challenge Rating': '恐怖等级',
    't:Race / Ancestry': '血脉',
    't:Headquarters': '宅邸',
    't:Habitat': '出没之地',
    't:Quest Giver': '委托人',
  },
};
