// Post-apocalypse: rust, dust and scavenged hope — Survivors, Zones, Jobs.
const postApocalypseVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Post-Apocalypse',
    'hint': 'Rust, dust and scavenged hope: Survivors, Zones, Jobs',
    'k.character': 'Survivor',
    'kp.character': 'Survivors',
    'k.location': 'Zone',
    'kp.location': 'Zones',
    'k.item': 'Salvage',
    'kp.item': 'Salvage',
    'k.creature': 'Mutant',
    'kp.creature': 'Mutants & Beasts',
    'k.faction': 'Tribe',
    'kp.faction': 'Tribes & Crews',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Age',
    'kp.era': 'Ages',
    'k.religion': 'Creed',
    'kp.religion': 'Creeds',
    'k.magicSystem': 'Mutation',
    'kp.magicSystem': 'Mutations',
    'k.technology': 'Old Tech',
    'kp.technology': 'Old Tech',
    'k.concept': 'Memory',
    'kp.concept': 'Memories',
    'k.loreDocument': 'Record',
    'kp.loreDocument': 'Old-World Records',
    'k.campaign': 'Journey',
    'kp.campaign': 'Journeys',
    'k.quest': 'Job',
    'kp.quest': 'Jobs',
    'k.session': 'Day',
    'kp.session': 'Days',
    't:Spell': 'Mutation Power',
    't:Spells': 'Mutation Powers',
    't:School': 'Strain',
    't:Casting Time': 'Activation',
    't:Components': 'Costs',
    't:Legendary Actions': 'Alpha Actions',
    't:Magic Items': 'Rare Salvage',
    't:Race / Ancestry': 'Origin',
    't:Class / Profession': 'Role',
    't:Currency': 'Barter / Caps',
    't:Source of Power': 'Mutagen',
    't:Headquarters': 'Stronghold',
    't:Ruler': 'Boss',
    't:Home / Base': 'Shelter',
    't:Quest Giver': 'Client',
    't:Rewards': 'Payment',
  },
  'ru': {
    'name': 'Постапокалипсис',
    'hint': 'Ржавчина, пыль и надежда: Выжившие, Зоны, Вылазки',
    'k.character': 'Выживший',
    'kp.character': 'Выжившие',
    'k.location': 'Зона',
    'kp.location': 'Зоны',
    'k.item': 'Хабар',
    'kp.item': 'Хабар',
    'k.creature': 'Мутант',
    'kp.creature': 'Мутанты и звери',
    'k.faction': 'Племя',
    'kp.faction': 'Племена и банды',
    'k.event': 'Происшествие',
    'kp.event': 'Происшествия',
    'k.era': 'Эра',
    'kp.era': 'Эры',
    'k.religion': 'Вера',
    'kp.religion': 'Верования',
    'k.magicSystem': 'Мутация',
    'kp.magicSystem': 'Мутации',
    'k.technology': 'Старая техника',
    'kp.technology': 'Старая техника',
    'k.concept': 'Воспоминание',
    'kp.concept': 'Воспоминания',
    'k.loreDocument': 'Запись',
    'kp.loreDocument': 'Записи старого мира',
    'k.campaign': 'Поход',
    'kp.campaign': 'Походы',
    'k.quest': 'Вылазка',
    'kp.quest': 'Вылазки',
    'k.session': 'День',
    'kp.session': 'Дни',
    't:Spell': 'Дар мутации',
    't:Spells': 'Дары мутаций',
    't:School': 'Штамм',
    't:Casting Time': 'Время активации',
    't:Components': 'Цена',
    't:Legendary Actions': 'Действия вожака',
    't:Magic Items': 'Редкий хабар',
    't:Race / Ancestry': 'Происхождение',
    't:Class / Profession': 'Роль',
    't:Currency': 'Бартер / крышки',
    't:Source of Power': 'Мутаген',
    't:Headquarters': 'Опорный пункт',
    't:Ruler': 'Главарь',
    't:Home / Base': 'Убежище',
    't:Quest Giver': 'Наниматель',
    't:Rewards': 'Оплата',
  },
  'de': {
    'name': 'Postapokalypse',
    'hint': 'Rost, Staub und letzte Hoffnung: Überlebende, Zonen, Jobs',
    'k.character': 'Überlebender',
    'kp.character': 'Überlebende',
    'k.location': 'Zone',
    'kp.location': 'Zonen',
    'k.item': 'Plündergut',
    'kp.item': 'Plündergut',
    'k.creature': 'Mutant',
    'kp.creature': 'Mutanten & Bestien',
    'k.faction': 'Stamm',
    'kp.faction': 'Stämme & Crews',
    'k.event': 'Vorfall',
    'kp.event': 'Vorfälle',
    'k.era': 'Zeitalter',
    'kp.era': 'Zeitalter',
    'k.religion': 'Glaube',
    'kp.religion': 'Glaubensrichtungen',
    'k.magicSystem': 'Mutation',
    'kp.magicSystem': 'Mutationen',
    'k.technology': 'Alttechnik',
    'kp.technology': 'Alttechnik',
    'k.concept': 'Erinnerung',
    'kp.concept': 'Erinnerungen',
    'k.loreDocument': 'Aufzeichnung',
    'kp.loreDocument': 'Altwelt-Akten',
    'k.campaign': 'Reise',
    'kp.campaign': 'Reisen',
    'k.quest': 'Job',
    'kp.quest': 'Jobs',
    'k.session': 'Tag',
    'kp.session': 'Tage',
    't:Spell': 'Mutationskraft',
    't:Spells': 'Mutationskräfte',
    't:School': 'Mutationslinie',
    't:Casting Time': 'Aktivierung',
    't:Components': 'Kosten',
    't:Legendary Actions': 'Alpha-Aktionen',
    't:Magic Items': 'Seltenes Plündergut',
    't:Race / Ancestry': 'Herkunft',
    't:Class / Profession': 'Rolle',
    't:Currency': 'Tausch / Kronkorken',
    't:Source of Power': 'Mutagen',
    't:Headquarters': 'Hochburg',
    't:Ruler': 'Boss',
    't:Home / Base': 'Unterschlupf',
    't:Quest Giver': 'Auftraggeber',
    't:Rewards': 'Bezahlung',
  },
  'fr': {
    'name': 'Post-apocalypse',
    'hint': 'Rouille, poussière et espoir : Survivants, Zones, Boulots',
    'k.character': 'Survivant',
    'kp.character': 'Survivants',
    'k.location': 'Zone',
    'kp.location': 'Zones',
    'k.item': 'Récup',
    'kp.item': 'Récup',
    'k.creature': 'Mutant',
    'kp.creature': 'Mutants et bêtes',
    'k.faction': 'Tribu',
    'kp.faction': 'Tribus et bandes',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Âge',
    'kp.era': 'Âges',
    'k.religion': 'Credo',
    'kp.religion': 'Credos',
    'k.magicSystem': 'Mutation',
    'kp.magicSystem': 'Mutations',
    'k.technology': 'Techno d\'avant',
    'kp.technology': 'Technos d\'avant',
    'k.concept': 'Souvenir',
    'kp.concept': 'Souvenirs',
    'k.loreDocument': 'Archive',
    'kp.loreDocument': 'Archives d\'avant',
    'k.campaign': 'Périple',
    'kp.campaign': 'Périples',
    'k.quest': 'Boulot',
    'kp.quest': 'Boulots',
    'k.session': 'Jour',
    'kp.session': 'Jours',
    't:Spell': 'Pouvoir mutant',
    't:Spells': 'Pouvoirs mutants',
    't:School': 'Souche',
    't:Casting Time': 'Activation',
    't:Components': 'Coûts',
    't:Legendary Actions': 'Actions d\'alpha',
    't:Magic Items': 'Récup rare',
    't:Race / Ancestry': 'Origine',
    't:Class / Profession': 'Rôle',
    't:Currency': 'Troc / capsules',
    't:Source of Power': 'Mutagène',
    't:Headquarters': 'Bastion',
    't:Ruler': 'Chef',
    't:Home / Base': 'Planque',
    't:Quest Giver': 'Commanditaire',
    't:Rewards': 'Paiement',
  },
  'zh': {
    'name': '末日废土',
    'hint': '锈蚀、尘土与残存希望：幸存者、地带、差事',
    'k.character': '幸存者',
    'kp.character': '幸存者',
    'k.location': '地带',
    'kp.location': '地带',
    'k.item': '物资',
    'kp.item': '物资',
    'k.creature': '变异体',
    'kp.creature': '变异体与野兽',
    'k.faction': '部落',
    'kp.faction': '部落与团伙',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '时代',
    'kp.era': '时代',
    'k.religion': '信条',
    'kp.religion': '信条',
    'k.magicSystem': '变异',
    'kp.magicSystem': '变异',
    'k.technology': '旧科技',
    'kp.technology': '旧科技',
    'k.concept': '记忆',
    'kp.concept': '记忆',
    'k.loreDocument': '记录',
    'kp.loreDocument': '旧世界档案',
    'k.campaign': '旅程',
    'kp.campaign': '旅程',
    'k.quest': '差事',
    'kp.quest': '差事',
    'k.session': '天',
    'kp.session': '天',
    't:Spell': '变异能力',
    't:Spells': '变异能力',
    't:School': '变异株',
    't:Casting Time': '激活时间',
    't:Components': '代价',
    't:Legendary Actions': '头领动作',
    't:Magic Items': '稀有物资',
    't:Race / Ancestry': '出身',
    't:Class / Profession': '职能',
    't:Currency': '以物易物 / 瓶盖',
    't:Source of Power': '诱变源',
    't:Headquarters': '据点',
    't:Ruler': '头目',
    't:Home / Base': '藏身处',
    't:Quest Giver': '雇主',
    't:Rewards': '报酬',
  },
};
