// Space opera: starships and distant suns — Crew, Waypoints, Missions.
const spaceOperaVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Space Opera',
    'hint': 'Starships and distant suns: Crew, Waypoints, Missions',
    'k.character': 'Crewmember',
    'kp.character': 'Crew & Contacts',
    'k.location': 'Waypoint',
    'kp.location': 'Waypoints',
    'k.item': 'Equipment',
    'kp.item': 'Equipment',
    'k.creature': 'Xenoform',
    'kp.creature': 'Xenofauna',
    'k.faction': 'Polity',
    'kp.faction': 'Polities & Corps',
    'k.event': 'Incident',
    'kp.event': 'Galactic Events',
    'k.era': 'Epoch',
    'kp.era': 'Epochs',
    'k.religion': 'Creed',
    'kp.religion': 'Creeds',
    'k.magicSystem': 'Psionic Discipline',
    'kp.magicSystem': 'Psionics',
    'k.technology': 'Tech',
    'kp.technology': 'Technologies',
    'k.concept': 'Datum',
    'kp.concept': 'Databank',
    'k.loreDocument': 'Codex Entry',
    'kp.loreDocument': 'Codex',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Mission',
    'kp.quest': 'Missions',
    'k.session': 'Episode',
    'kp.session': 'Episodes',
    't:Spell': 'Psionic Power',
    't:Spells': 'Psionic Powers',
    't:School': 'Discipline',
    't:Casting Time': 'Activation',
    't:Components': 'Requirements',
    't:Legendary Actions': 'Signature Actions',
    't:Magic Items': 'Relic Tech',
    't:Race / Ancestry': 'Species',
    't:Class / Profession': 'Role / Specialty',
    't:Deities': 'Creeds',
    't:Currency': 'Credits',
    't:Source of Power': 'Psionic Source',
    't:Home / Base': 'Home Port',
    't:Habitat': 'Biome',
    't:Abilities & Magic': 'Abilities & Psionics',
  },
  'ru': {
    'name': 'Космоопера',
    'hint': 'Звездолёты и далёкие солнца: Экипаж, Точки маршрута, Миссии',
    'k.character': 'Член экипажа',
    'kp.character': 'Экипаж и контакты',
    'k.location': 'Точка маршрута',
    'kp.location': 'Точки маршрута',
    'k.item': 'Снаряжение',
    'kp.item': 'Снаряжение',
    'k.creature': 'Ксеноформа',
    'kp.creature': 'Ксенофауна',
    'k.faction': 'Держава',
    'kp.faction': 'Державы и корпорации',
    'k.event': 'Инцидент',
    'kp.event': 'Галактические события',
    'k.era': 'Эпоха',
    'kp.era': 'Эпохи',
    'k.religion': 'Вероучение',
    'kp.religion': 'Вероучения',
    'k.magicSystem': 'Пси-дисциплина',
    'kp.magicSystem': 'Псионика',
    'k.technology': 'Технология',
    'kp.technology': 'Технологии',
    'k.concept': 'Запись данных',
    'kp.concept': 'Банк данных',
    'k.loreDocument': 'Статья кодекса',
    'kp.loreDocument': 'Кодекс',
    'k.campaign': 'Сага',
    'kp.campaign': 'Саги',
    'k.quest': 'Миссия',
    'kp.quest': 'Миссии',
    'k.session': 'Эпизод',
    'kp.session': 'Эпизоды',
    't:Spell': 'Пси-способность',
    't:Spells': 'Пси-способности',
    't:School': 'Дисциплина',
    't:Casting Time': 'Время активации',
    't:Components': 'Требования',
    't:Legendary Actions': 'Коронные действия',
    't:Magic Items': 'Реликтовые технологии',
    't:Race / Ancestry': 'Вид',
    't:Class / Profession': 'Роль / специализация',
    't:Deities': 'Вероучения',
    't:Currency': 'Кредиты',
    't:Source of Power': 'Источник пси-силы',
    't:Home / Base': 'Порт приписки',
    't:Habitat': 'Биом',
    't:Abilities & Magic': 'Способности и псионика',
  },
  'de': {
    'name': 'Space Opera',
    'hint': 'Raumschiffe und ferne Sonnen: Crew, Wegpunkte, Missionen',
    'k.character': 'Crewmitglied',
    'kp.character': 'Crew & Kontakte',
    'k.location': 'Wegpunkt',
    'kp.location': 'Wegpunkte',
    'k.item': 'Ausrüstung',
    'kp.item': 'Ausrüstung',
    'k.creature': 'Xenoform',
    'kp.creature': 'Xenofauna',
    'k.faction': 'Sternenreich',
    'kp.faction': 'Reiche & Konzerne',
    'k.event': 'Zwischenfall',
    'kp.event': 'Galaktische Ereignisse',
    'k.era': 'Epoche',
    'kp.era': 'Epochen',
    'k.religion': 'Glaubenslehre',
    'kp.religion': 'Glaubenslehren',
    'k.magicSystem': 'Psi-Disziplin',
    'kp.magicSystem': 'Psionik',
    'k.technology': 'Technologie',
    'kp.technology': 'Technologien',
    'k.concept': 'Datensatz',
    'kp.concept': 'Datenbank',
    'k.loreDocument': 'Kodex-Eintrag',
    'kp.loreDocument': 'Kodex',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Mission',
    'kp.quest': 'Missionen',
    'k.session': 'Episode',
    'kp.session': 'Episoden',
    't:Spell': 'Psi-Kraft',
    't:Spells': 'Psi-Kräfte',
    't:School': 'Disziplin',
    't:Casting Time': 'Aktivierung',
    't:Components': 'Voraussetzungen',
    't:Legendary Actions': 'Signatur-Aktionen',
    't:Magic Items': 'Relikttechnik',
    't:Race / Ancestry': 'Spezies',
    't:Class / Profession': 'Rolle / Fachgebiet',
    't:Deities': 'Glaubenslehren',
    't:Currency': 'Credits',
    't:Source of Power': 'Psi-Quelle',
    't:Home / Base': 'Heimathafen',
    't:Habitat': 'Biom',
    't:Abilities & Magic': 'Fähigkeiten & Psionik',
  },
  'fr': {
    'name': 'Space opera',
    'hint': 'Vaisseaux et soleils lointains : Équipage, Escales, Missions',
    'k.character': 'Membre d\'équipage',
    'kp.character': 'Équipage et contacts',
    'k.location': 'Escale',
    'kp.location': 'Escales',
    'k.item': 'Équipement',
    'kp.item': 'Équipement',
    'k.creature': 'Xénoforme',
    'kp.creature': 'Xénofaune',
    'k.faction': 'Puissance',
    'kp.faction': 'Puissances et corpos',
    'k.event': 'Incident',
    'kp.event': 'Événements galactiques',
    'k.era': 'Ère',
    'kp.era': 'Ères',
    'k.religion': 'Credo',
    'kp.religion': 'Credos',
    'k.magicSystem': 'Discipline psionique',
    'kp.magicSystem': 'Psionique',
    'k.technology': 'Technologie',
    'kp.technology': 'Technologies',
    'k.concept': 'Donnée',
    'kp.concept': 'Banque de données',
    'k.loreDocument': 'Entrée du codex',
    'kp.loreDocument': 'Codex',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Mission',
    'kp.quest': 'Missions',
    'k.session': 'Épisode',
    'kp.session': 'Épisodes',
    't:Spell': 'Pouvoir psionique',
    't:Spells': 'Pouvoirs psioniques',
    't:School': 'Discipline',
    't:Casting Time': 'Activation',
    't:Components': 'Prérequis',
    't:Legendary Actions': 'Actions signature',
    't:Magic Items': 'Technologies reliques',
    't:Race / Ancestry': 'Espèce',
    't:Class / Profession': 'Rôle / Spécialité',
    't:Deities': 'Credos',
    't:Currency': 'Crédits',
    't:Source of Power': 'Source psionique',
    't:Home / Base': 'Port d\'attache',
    't:Habitat': 'Biome',
    't:Abilities & Magic': 'Capacités et psionique',
  },
  'zh': {
    'name': '太空歌剧',
    'hint': '星舰与遥远恒星：船员、航点、任务',
    'k.character': '船员',
    'kp.character': '船员与联络人',
    'k.location': '航点',
    'kp.location': '航点',
    'k.item': '装备',
    'kp.item': '装备',
    'k.creature': '异星生物',
    'kp.creature': '异星生物',
    'k.faction': '政体',
    'kp.faction': '政体与公司',
    'k.event': '事件',
    'kp.event': '银河事件',
    'k.era': '纪元',
    'kp.era': '纪元',
    'k.religion': '信条',
    'kp.religion': '信条',
    'k.magicSystem': '灵能流派',
    'kp.magicSystem': '灵能',
    'k.technology': '科技',
    'kp.technology': '科技',
    'k.concept': '数据条目',
    'kp.concept': '数据库',
    'k.loreDocument': '典籍条目',
    'kp.loreDocument': '典籍',
    'k.campaign': '史诗',
    'kp.campaign': '史诗',
    'k.quest': '任务',
    'kp.quest': '任务',
    'k.session': '剧集',
    'kp.session': '剧集',
    't:Spell': '灵能技',
    't:Spells': '灵能技',
    't:School': '流派',
    't:Casting Time': '激活时间',
    't:Components': '需求',
    't:Legendary Actions': '招牌动作',
    't:Magic Items': '遗物科技',
    't:Race / Ancestry': '物种',
    't:Class / Profession': '职能 / 专长',
    't:Deities': '信条',
    't:Currency': '信用点',
    't:Source of Power': '灵能来源',
    't:Home / Base': '母港',
    't:Habitat': '生物群系',
    't:Abilities & Magic': '能力与灵能',
  },
};
