// Steampunk: brass, steam and gaslight — Personages, Contraptions, Expeditions.
const steampunkVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Steampunk',
    'hint': 'Brass, steam and gaslight: Personages, Contraptions, Expeditions',
    'k.character': 'Personage',
    'kp.character': 'Personages',
    'k.location': 'Locale',
    'kp.location': 'Locales',
    'k.item': 'Contraption',
    'kp.item': 'Contraptions',
    'k.creature': 'Specimen',
    'kp.creature': 'Specimens',
    'k.faction': 'Guild',
    'kp.faction': 'Guilds & Societies',
    'k.event': 'Affair',
    'kp.event': 'Affairs',
    'k.era': 'Epoch',
    'kp.era': 'Epochs',
    'k.religion': 'Creed',
    'kp.religion': 'Creeds',
    'k.magicSystem': 'Aetheric Science',
    'kp.magicSystem': 'Aetheric Sciences',
    'k.technology': 'Invention',
    'kp.technology': 'Inventions',
    'k.concept': 'Theory',
    'kp.concept': 'Theories',
    'k.loreDocument': 'Journal',
    'kp.loreDocument': 'Journals',
    'k.campaign': 'Expedition',
    'kp.campaign': 'Expeditions',
    'k.quest': 'Commission',
    'kp.quest': 'Commissions',
    'k.session': 'Installment',
    'kp.session': 'Installments',
    't:Spell': 'Formula',
    't:Spells': 'Formulae',
    't:School': 'Discipline',
    't:Casting Time': 'Preparation',
    't:Components': 'Apparatus',
    't:Magic Items': 'Marvels',
    't:Legendary Actions': 'Signature Feats',
    't:Race / Ancestry': 'Lineage',
    't:Class / Profession': 'Vocation',
    't:Source of Power': 'Energy Source',
    't:Rules & Limits': 'Laws & Limits',
    't:Abilities & Magic': 'Talents & Science',
    't:Headquarters': 'Guildhall',
    't:Challenge Rating': 'Threat Rating',
  },
  'ru': {
    'name': 'Стимпанк',
    'hint': 'Латунь, пар и газовые фонари: Персоны, Механизмы, Экспедиции',
    'k.character': 'Персона',
    'kp.character': 'Персоны',
    'k.location': 'Место',
    'kp.location': 'Места',
    'k.item': 'Механизм',
    'kp.item': 'Механизмы',
    'k.creature': 'Образец',
    'kp.creature': 'Образцы',
    'k.faction': 'Гильдия',
    'kp.faction': 'Гильдии и общества',
    'k.event': 'Происшествие',
    'kp.event': 'Происшествия',
    'k.era': 'Эпоха',
    'kp.era': 'Эпохи',
    'k.religion': 'Вероучение',
    'kp.religion': 'Вероучения',
    'k.magicSystem': 'Эфирная наука',
    'kp.magicSystem': 'Эфирные науки',
    'k.technology': 'Изобретение',
    'kp.technology': 'Изобретения',
    'k.concept': 'Теория',
    'kp.concept': 'Теории',
    'k.loreDocument': 'Журнал',
    'kp.loreDocument': 'Журналы',
    'k.campaign': 'Экспедиция',
    'kp.campaign': 'Экспедиции',
    'k.quest': 'Поручение',
    'kp.quest': 'Поручения',
    'k.session': 'Выпуск',
    'kp.session': 'Выпуски',
    't:Spell': 'Формула',
    't:Spells': 'Формулы',
    't:School': 'Дисциплина',
    't:Casting Time': 'Подготовка',
    't:Components': 'Аппаратура',
    't:Magic Items': 'Диковины',
    't:Legendary Actions': 'Коронные приёмы',
    't:Race / Ancestry': 'Происхождение',
    't:Class / Profession': 'Род занятий',
    't:Source of Power': 'Источник энергии',
    't:Rules & Limits': 'Законы и пределы',
    't:Abilities & Magic': 'Таланты и наука',
    't:Headquarters': 'Штаб-квартира',
    't:Challenge Rating': 'Уровень угрозы',
  },
  'de': {
    'name': 'Steampunk',
    'hint': 'Messing, Dampf und Gaslicht: Persönlichkeiten, Apparate, Expeditionen',
    'k.character': 'Persönlichkeit',
    'kp.character': 'Persönlichkeiten',
    'k.location': 'Schauplatz',
    'kp.location': 'Schauplätze',
    'k.item': 'Apparat',
    'kp.item': 'Apparate',
    'k.creature': 'Exemplar',
    'kp.creature': 'Exemplare',
    'k.faction': 'Gilde',
    'kp.faction': 'Gilden & Zirkel',
    'k.event': 'Begebenheit',
    'kp.event': 'Begebenheiten',
    'k.era': 'Epoche',
    'kp.era': 'Epochen',
    'k.religion': 'Bekenntnis',
    'kp.religion': 'Bekenntnisse',
    'k.magicSystem': 'Ätherlehre',
    'kp.magicSystem': 'Ätherlehren',
    'k.technology': 'Erfindung',
    'kp.technology': 'Erfindungen',
    'k.concept': 'Theorie',
    'kp.concept': 'Theorien',
    'k.loreDocument': 'Tagebuch',
    'kp.loreDocument': 'Tagebücher',
    'k.campaign': 'Expedition',
    'kp.campaign': 'Expeditionen',
    'k.quest': 'Auftrag',
    'kp.quest': 'Aufträge',
    'k.session': 'Folge',
    'kp.session': 'Folgen',
    't:Spell': 'Formel',
    't:Spells': 'Formeln',
    't:School': 'Disziplin',
    't:Casting Time': 'Vorbereitung',
    't:Components': 'Apparatur',
    't:Magic Items': 'Wunderwerke',
    't:Legendary Actions': 'Glanzstücke',
    't:Race / Ancestry': 'Abstammung',
    't:Class / Profession': 'Beruf',
    't:Source of Power': 'Energiequelle',
    't:Rules & Limits': 'Gesetze & Grenzen',
    't:Abilities & Magic': 'Talente & Wissenschaft',
    't:Headquarters': 'Gildenhaus',
    't:Challenge Rating': 'Gefahrenstufe',
  },
  'fr': {
    'name': 'Steampunk',
    'hint': 'Laiton, vapeur et becs de gaz : Personnages, Engins, Expéditions',
    'k.character': 'Personnage',
    'kp.character': 'Personnages',
    'k.location': 'Lieu',
    'kp.location': 'Lieux',
    'k.item': 'Engin',
    'kp.item': 'Engins',
    'k.creature': 'Spécimen',
    'kp.creature': 'Spécimens',
    'k.faction': 'Guilde',
    'kp.faction': 'Guildes et sociétés',
    'k.event': 'Affaire',
    'kp.event': 'Affaires',
    'k.era': 'Époque',
    'kp.era': 'Époques',
    'k.religion': 'Confession',
    'kp.religion': 'Confessions',
    'k.magicSystem': 'Science éthérique',
    'kp.magicSystem': 'Sciences éthériques',
    'k.technology': 'Invention',
    'kp.technology': 'Inventions',
    'k.concept': 'Théorie',
    'kp.concept': 'Théories',
    'k.loreDocument': 'Journal',
    'kp.loreDocument': 'Journaux',
    'k.campaign': 'Expédition',
    'kp.campaign': 'Expéditions',
    'k.quest': 'Mandat',
    'kp.quest': 'Mandats',
    'k.session': 'Épisode',
    'kp.session': 'Épisodes',
    't:Spell': 'Formule',
    't:Spells': 'Formules',
    't:School': 'Discipline',
    't:Casting Time': 'Préparation',
    't:Components': 'Appareillage',
    't:Magic Items': 'Merveilles',
    't:Legendary Actions': 'Coups de maître',
    't:Race / Ancestry': 'Lignée',
    't:Class / Profession': 'Vocation',
    't:Source of Power': 'Source d\'énergie',
    't:Rules & Limits': 'Lois et limites',
    't:Abilities & Magic': 'Talents et science',
    't:Headquarters': 'Siège',
    't:Challenge Rating': 'Niveau de menace',
  },
  'zh': {
    'name': '蒸汽朋克',
    'hint': '黄铜、蒸汽与煤气灯：名士、奇械、探险',
    'k.character': '名士',
    'kp.character': '名士',
    'k.location': '场所',
    'kp.location': '场所',
    'k.item': '奇械',
    'kp.item': '奇械',
    'k.creature': '标本',
    'kp.creature': '标本',
    'k.faction': '行会',
    'kp.faction': '行会与学会',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '纪元',
    'kp.era': '纪元',
    'k.religion': '信条',
    'kp.religion': '信条',
    'k.magicSystem': '以太科学',
    'kp.magicSystem': '以太科学',
    'k.technology': '发明',
    'kp.technology': '发明',
    'k.concept': '理论',
    'kp.concept': '理论',
    'k.loreDocument': '日志',
    'kp.loreDocument': '日志',
    'k.campaign': '探险',
    'kp.campaign': '探险',
    'k.quest': '委托',
    'kp.quest': '委托',
    'k.session': '连载',
    'kp.session': '连载',
    't:Spell': '公式',
    't:Spells': '公式',
    't:School': '学科',
    't:Casting Time': '准备时间',
    't:Components': '器材',
    't:Magic Items': '奇物',
    't:Legendary Actions': '绝技',
    't:Race / Ancestry': '血统',
    't:Class / Profession': '职业',
    't:Source of Power': '能源',
    't:Rules & Limits': '定律与局限',
    't:Abilities & Magic': '才能与科学',
    't:Headquarters': '会馆',
    't:Challenge Rating': '威胁等级',
  },
};
