// Urban fantasy: a hidden city behind the veil — Supernaturals, Courts, Cases.
const urbanFantasyVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Urban Fantasy',
    'hint': 'Secrets behind the veil: Supernaturals, Courts, Cases',
    'k.character': 'Person',
    'kp.character': 'People',
    'k.location': 'Site',
    'kp.location': 'Sites',
    'k.item': 'Artifact',
    'kp.item': 'Artifacts',
    'k.creature': 'Supernatural',
    'kp.creature': 'Supernaturals',
    'k.faction': 'Court',
    'kp.faction': 'Courts & Factions',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Era',
    'kp.era': 'Hidden History',
    'k.religion': 'Tradition',
    'kp.religion': 'Traditions',
    'k.magicSystem': 'Practice',
    'kp.magicSystem': 'Practices',
    'k.technology': 'Gadget',
    'kp.technology': 'Gadgets',
    'k.concept': 'Secret',
    'kp.concept': 'Secrets',
    'k.loreDocument': 'Case Note',
    'kp.loreDocument': 'Case Notes',
    'k.campaign': 'Season',
    'kp.campaign': 'Seasons',
    'k.quest': 'Case',
    'kp.quest': 'Cases',
    'k.session': 'Episode',
    'kp.session': 'Episodes',
    't:Spell': 'Working',
    't:Spells': 'Workings',
    't:School': 'Practice',
    't:Casting Time': 'Ritual Time',
    't:Components': 'Focus',
    't:Magic Items': 'Artifacts',
    't:Race / Ancestry': 'Nature',
    't:Class / Profession': 'Occupation',
    't:Deities': 'Powers That Be',
    't:Deity': 'Patron',
    't:Challenge Rating': 'Threat Level',
    't:Headquarters': 'Haven',
    't:Home / Base': 'Safehouse',
    't:Alignment': 'Allegiance',
    't:Habitat': 'Haunts',
  },
  'ru': {
    'name': 'Городское фэнтези',
    'hint': 'Тайны за завесой: Сущности, Дворы, Дела',
    'k.character': 'Человек',
    'kp.character': 'Люди',
    'k.location': 'Место',
    'kp.location': 'Места',
    'k.item': 'Артефакт',
    'kp.item': 'Артефакты',
    'k.creature': 'Сущность',
    'kp.creature': 'Сущности',
    'k.faction': 'Двор',
    'kp.faction': 'Дворы и фракции',
    'k.event': 'Инцидент',
    'kp.event': 'Инциденты',
    'k.era': 'Эпоха',
    'kp.era': 'Тайная история',
    'k.religion': 'Традиция',
    'kp.religion': 'Традиции',
    'k.magicSystem': 'Практика',
    'kp.magicSystem': 'Практики',
    'k.technology': 'Гаджет',
    'kp.technology': 'Гаджеты',
    'k.concept': 'Тайна',
    'kp.concept': 'Тайны',
    'k.loreDocument': 'Запись по делу',
    'kp.loreDocument': 'Записи по делам',
    'k.campaign': 'Сезон',
    'kp.campaign': 'Сезоны',
    'k.quest': 'Дело',
    'kp.quest': 'Дела',
    'k.session': 'Серия',
    'kp.session': 'Серии',
    't:Spell': 'Ворожба',
    't:Spells': 'Чары',
    't:School': 'Практика',
    't:Casting Time': 'Время ритуала',
    't:Components': 'Фокус',
    't:Magic Items': 'Артефакты',
    't:Race / Ancestry': 'Природа',
    't:Class / Profession': 'Род занятий',
    't:Deities': 'Высшие силы',
    't:Deity': 'Покровитель',
    't:Challenge Rating': 'Уровень угрозы',
    't:Headquarters': 'Оплот',
    't:Home / Base': 'Укрытие',
    't:Alignment': 'Сторона',
    't:Habitat': 'Места обитания',
  },
  'de': {
    'name': 'Urban Fantasy',
    'hint': 'Geheimnisse hinter dem Schleier: Übernatürliche, Höfe, Fälle',
    'k.character': 'Person',
    'kp.character': 'Leute',
    'k.location': 'Ort',
    'kp.location': 'Orte',
    'k.item': 'Artefakt',
    'kp.item': 'Artefakte',
    'k.creature': 'Übernatürlicher',
    'kp.creature': 'Übernatürliche',
    'k.faction': 'Hof',
    'kp.faction': 'Höfe & Fraktionen',
    'k.event': 'Vorfall',
    'kp.event': 'Vorfälle',
    'k.era': 'Ära',
    'kp.era': 'Verborgene Geschichte',
    'k.religion': 'Tradition',
    'kp.religion': 'Traditionen',
    'k.magicSystem': 'Praxis',
    'kp.magicSystem': 'Praktiken',
    'k.technology': 'Gadget',
    'kp.technology': 'Gadgets',
    'k.concept': 'Geheimnis',
    'kp.concept': 'Geheimnisse',
    'k.loreDocument': 'Fallnotiz',
    'kp.loreDocument': 'Fallnotizen',
    'k.campaign': 'Staffel',
    'kp.campaign': 'Staffeln',
    'k.quest': 'Fall',
    'kp.quest': 'Fälle',
    'k.session': 'Folge',
    'kp.session': 'Folgen',
    't:Spell': 'Zauberwerk',
    't:Spells': 'Zauberwerke',
    't:School': 'Praxis',
    't:Casting Time': 'Ritualdauer',
    't:Components': 'Fokus',
    't:Magic Items': 'Artefakte',
    't:Race / Ancestry': 'Natur',
    't:Class / Profession': 'Beruf',
    't:Deities': 'Höhere Mächte',
    't:Deity': 'Schutzmacht',
    't:Challenge Rating': 'Gefahrenstufe',
    't:Headquarters': 'Zuflucht',
    't:Home / Base': 'Unterschlupf',
    't:Alignment': 'Loyalität',
    't:Habitat': 'Revier',
  },
  'fr': {
    'name': 'Fantasy urbaine',
    'hint': 'Secrets derrière le voile : Surnaturels, Cours, Enquêtes',
    'k.character': 'Personne',
    'kp.character': 'Gens',
    'k.location': 'Site',
    'kp.location': 'Sites',
    'k.item': 'Artefact',
    'kp.item': 'Artefacts',
    'k.creature': 'Surnaturel',
    'kp.creature': 'Surnaturels',
    'k.faction': 'Cour',
    'kp.faction': 'Cours et factions',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Ère',
    'kp.era': 'Histoire secrète',
    'k.religion': 'Tradition',
    'kp.religion': 'Traditions',
    'k.magicSystem': 'Pratique',
    'kp.magicSystem': 'Pratiques',
    'k.technology': 'Gadget',
    'kp.technology': 'Gadgets',
    'k.concept': 'Secret',
    'kp.concept': 'Secrets',
    'k.loreDocument': 'Note d\'enquête',
    'kp.loreDocument': 'Notes d\'enquête',
    'k.campaign': 'Saison',
    'kp.campaign': 'Saisons',
    'k.quest': 'Enquête',
    'kp.quest': 'Enquêtes',
    'k.session': 'Épisode',
    'kp.session': 'Épisodes',
    't:Spell': 'Sortilège',
    't:Spells': 'Sortilèges',
    't:School': 'Pratique',
    't:Casting Time': 'Durée du rituel',
    't:Components': 'Focalisateur',
    't:Magic Items': 'Artefacts',
    't:Race / Ancestry': 'Nature',
    't:Class / Profession': 'Métier',
    't:Deities': 'Puissances',
    't:Deity': 'Patron',
    't:Challenge Rating': 'Niveau de menace',
    't:Headquarters': 'Repaire',
    't:Home / Base': 'Planque',
    't:Alignment': 'Allégeance',
    't:Habitat': 'Territoire',
  },
  'zh': {
    'name': '都市奇幻',
    'hint': '帷幕后的秘密：异类、宫廷、案件',
    'k.character': '人物',
    'kp.character': '人物',
    'k.location': '地点',
    'kp.location': '地点',
    'k.item': '神器',
    'kp.item': '神器',
    'k.creature': '异类',
    'kp.creature': '异类',
    'k.faction': '宫廷',
    'kp.faction': '宫廷与派系',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '时代',
    'kp.era': '隐秘历史',
    'k.religion': '传承',
    'kp.religion': '传承',
    'k.magicSystem': '术法',
    'kp.magicSystem': '术法',
    'k.technology': '装置',
    'kp.technology': '装置',
    'k.concept': '秘密',
    'kp.concept': '秘密',
    'k.loreDocument': '案件笔记',
    'kp.loreDocument': '案件笔记',
    'k.campaign': '剧季',
    'kp.campaign': '剧季',
    'k.quest': '案件',
    'kp.quest': '案件',
    'k.session': '剧集',
    'kp.session': '剧集',
    't:Spell': '术式',
    't:Spells': '术式',
    't:School': '流派',
    't:Casting Time': '施术时间',
    't:Components': '媒介',
    't:Magic Items': '神器',
    't:Race / Ancestry': '本质',
    't:Class / Profession': '职业',
    't:Deities': '上位存在',
    't:Deity': '守护者',
    't:Challenge Rating': '威胁等级',
    't:Headquarters': '据点',
    't:Home / Base': '安全屋',
    't:Alignment': '立场',
    't:Habitat': '出没地',
  },
};
