// Wild west: dust, lead and weird lore — Outfits, Bounties, Trails.
const wildWestVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Wild West',
    'hint': 'Dust, lead and weird lore: Outfits, Bounties, Trails',
    'k.character': 'Person',
    'kp.character': 'Folks',
    'k.location': 'Landmark',
    'kp.location': 'Landmarks',
    'k.item': 'Gear',
    'kp.item': 'Gear & Goods',
    'k.creature': 'Critter',
    'kp.creature': 'Critters',
    'k.faction': 'Outfit',
    'kp.faction': 'Outfits',
    'k.event': 'Happening',
    'kp.event': 'Happenings',
    'k.era': 'Era',
    'kp.era': 'Eras',
    'k.religion': 'Faith',
    'kp.religion': 'Faiths',
    'k.magicSystem': 'Hex',
    'kp.magicSystem': 'Hexes',
    'k.technology': 'Contraption',
    'kp.technology': 'Contraptions',
    'k.concept': 'Legend',
    'kp.concept': 'Legends',
    'k.loreDocument': 'Dispatch',
    'kp.loreDocument': 'Dispatches',
    'k.campaign': 'Trail',
    'kp.campaign': 'Trails',
    'k.quest': 'Bounty',
    'kp.quest': 'Bounties',
    'k.session': 'Ride',
    'kp.session': 'Rides',
    't:Spell': 'Hex',
    't:Spells': 'Hexes',
    't:Casting Time': 'Draw Time',
    't:Components': 'Fixings',
    't:Magic Items': 'Uncanny Goods',
    't:Currency': 'Dollars',
    't:Rewards': 'Bounty Reward',
    't:Headquarters': 'Hideout',
    't:Home / Base': 'Homestead',
    't:Class / Profession': 'Trade',
    't:Ruler': 'Boss',
    't:Government': 'Law',
    't:Quest Giver': 'Employer',
    't:Title / Epithet': 'Moniker',
    't:Weapons': 'Irons',
  },
  'ru': {
    'name': 'Дикий Запад',
    'hint': 'Пыль, свинец и жуткие байки: Банды, Награды, Тропы',
    'k.character': 'Человек',
    'kp.character': 'Люди',
    'k.location': 'Место',
    'kp.location': 'Места',
    'k.item': 'Снаряжение',
    'kp.item': 'Снаряжение и товары',
    'k.creature': 'Тварь',
    'kp.creature': 'Твари',
    'k.faction': 'Банда',
    'kp.faction': 'Банды',
    'k.event': 'Происшествие',
    'kp.event': 'Происшествия',
    'k.era': 'Эпоха',
    'kp.era': 'Эпохи',
    'k.religion': 'Вера',
    'kp.religion': 'Веры',
    'k.magicSystem': 'Заговор',
    'kp.magicSystem': 'Заговоры',
    'k.technology': 'Механизм',
    'kp.technology': 'Механизмы',
    'k.concept': 'Легенда',
    'kp.concept': 'Легенды',
    'k.loreDocument': 'Депеша',
    'kp.loreDocument': 'Депеши',
    'k.campaign': 'Тропа',
    'kp.campaign': 'Тропы',
    'k.quest': 'Награда',
    'kp.quest': 'Награды',
    'k.session': 'Выезд',
    'kp.session': 'Выезды',
    't:Spell': 'Заговор',
    't:Spells': 'Заговоры',
    't:Casting Time': 'Время выхвата',
    't:Components': 'Припасы',
    't:Magic Items': 'Диковины',
    't:Currency': 'Доллары',
    't:Rewards': 'Награда за голову',
    't:Headquarters': 'Логово',
    't:Home / Base': 'Пристанище',
    't:Class / Profession': 'Ремесло',
    't:Ruler': 'Хозяин',
    't:Government': 'Закон',
    't:Quest Giver': 'Наниматель',
    't:Title / Epithet': 'Прозвище',
    't:Weapons': 'Стволы',
  },
  'de': {
    'name': 'Wilder Westen',
    'hint': 'Staub, Blei und unheimliche Sagen: Banden, Kopfgelder, Trails',
    'k.character': 'Person',
    'kp.character': 'Leute',
    'k.location': 'Landmarke',
    'kp.location': 'Landmarken',
    'k.item': 'Ausrüstung',
    'kp.item': 'Ausrüstung & Waren',
    'k.creature': 'Viech',
    'kp.creature': 'Viecher',
    'k.faction': 'Bande',
    'kp.faction': 'Banden',
    'k.event': 'Ereignis',
    'kp.event': 'Ereignisse',
    'k.era': 'Ära',
    'kp.era': 'Ären',
    'k.religion': 'Glaube',
    'kp.religion': 'Glaubensrichtungen',
    'k.magicSystem': 'Hexerei',
    'kp.magicSystem': 'Hexereien',
    'k.technology': 'Apparat',
    'kp.technology': 'Apparate',
    'k.concept': 'Legende',
    'kp.concept': 'Legenden',
    'k.loreDocument': 'Depesche',
    'kp.loreDocument': 'Depeschen',
    'k.campaign': 'Trail',
    'kp.campaign': 'Trails',
    'k.quest': 'Kopfgeld',
    'kp.quest': 'Kopfgelder',
    'k.session': 'Ritt',
    'kp.session': 'Ritte',
    't:Spell': 'Hexerei',
    't:Spells': 'Hexereien',
    't:Casting Time': 'Ziehzeit',
    't:Components': 'Zutaten',
    't:Magic Items': 'Seltsame Waren',
    't:Currency': 'Dollar',
    't:Rewards': 'Kopfgeld',
    't:Headquarters': 'Versteck',
    't:Home / Base': 'Heimstatt',
    't:Class / Profession': 'Gewerbe',
    't:Ruler': 'Boss',
    't:Government': 'Gesetz',
    't:Quest Giver': 'Auftraggeber',
    't:Title / Epithet': 'Spitzname',
    't:Weapons': 'Schießeisen',
  },
  'fr': {
    'name': 'Far West',
    'hint': 'Poussière, plomb et légendes étranges : Bandes, Primes, Pistes',
    'k.character': 'Personne',
    'kp.character': 'Gens',
    'k.location': 'Lieu-dit',
    'kp.location': 'Lieux-dits',
    'k.item': 'Matériel',
    'kp.item': 'Matériel et denrées',
    'k.creature': 'Bestiole',
    'kp.creature': 'Bestioles',
    'k.faction': 'Bande',
    'kp.faction': 'Bandes',
    'k.event': 'Événement',
    'kp.event': 'Événements',
    'k.era': 'Ère',
    'kp.era': 'Ères',
    'k.religion': 'Croyance',
    'kp.religion': 'Croyances',
    'k.magicSystem': 'Maléfice',
    'kp.magicSystem': 'Maléfices',
    'k.technology': 'Engin',
    'kp.technology': 'Engins',
    'k.concept': 'Légende',
    'kp.concept': 'Légendes',
    'k.loreDocument': 'Dépêche',
    'kp.loreDocument': 'Dépêches',
    'k.campaign': 'Piste',
    'kp.campaign': 'Pistes',
    'k.quest': 'Prime',
    'kp.quest': 'Primes',
    'k.session': 'Chevauchée',
    'kp.session': 'Chevauchées',
    't:Spell': 'Maléfice',
    't:Spells': 'Maléfices',
    't:Casting Time': 'Temps de dégaine',
    't:Components': 'Ingrédients',
    't:Magic Items': 'Curiosités',
    't:Currency': 'Dollars',
    't:Rewards': 'Prime',
    't:Headquarters': 'Planque',
    't:Home / Base': 'Ranch',
    't:Class / Profession': 'Métier',
    't:Ruler': 'Patron',
    't:Government': 'Loi',
    't:Quest Giver': 'Commanditaire',
    't:Title / Epithet': 'Surnom',
    't:Weapons': 'Flingues',
  },
  'zh': {
    'name': '狂野西部',
    'hint': '尘土、铅弹与怪谈：帮派、赏金、路途',
    'k.character': '人物',
    'kp.character': '众人',
    'k.location': '地标',
    'kp.location': '地标',
    'k.item': '装备',
    'kp.item': '装备与货物',
    'k.creature': '野物',
    'kp.creature': '野物',
    'k.faction': '帮派',
    'kp.faction': '帮派',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '年代',
    'kp.era': '年代',
    'k.religion': '信仰',
    'kp.religion': '信仰',
    'k.magicSystem': '巫咒',
    'kp.magicSystem': '巫咒',
    'k.technology': '奇械',
    'kp.technology': '奇械',
    'k.concept': '传说',
    'kp.concept': '传说',
    'k.loreDocument': '电报',
    'kp.loreDocument': '电报',
    'k.campaign': '路途',
    'kp.campaign': '路途',
    'k.quest': '赏金',
    'kp.quest': '赏金',
    'k.session': '骑程',
    'kp.session': '骑程',
    't:Spell': '巫咒',
    't:Spells': '巫咒',
    't:Casting Time': '拔枪时间',
    't:Components': '材料',
    't:Magic Items': '怪异物件',
    't:Currency': '美元',
    't:Rewards': '赏金',
    't:Headquarters': '藏身处',
    't:Home / Base': '家宅',
    't:Class / Profession': '营生',
    't:Ruler': '老大',
    't:Government': '法律',
    't:Quest Giver': '雇主',
    't:Title / Epithet': '外号',
    't:Weapons': '枪械',
  },
};
