// Wuxia / xianxia: a jianghu of blades and qi — Sects, Martial Arts, Scrolls.
const wuxiaVocab = <String, Map<String, String>>{
  'en': {
    'name': 'Wuxia',
    'hint': 'A jianghu of blades and qi: Sects, Martial Arts, Scrolls',
    'k.character': 'Hero',
    'kp.character': 'Heroes & Villains',
    'k.location': 'Place',
    'kp.location': 'Rivers & Lakes',
    'k.item': 'Treasure',
    'kp.item': 'Treasures',
    'k.creature': 'Spirit Beast',
    'kp.creature': 'Spirit Beasts',
    'k.faction': 'Sect',
    'kp.faction': 'Sects & Clans',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Dynasty',
    'kp.era': 'Dynasties',
    'k.religion': 'Teaching',
    'kp.religion': 'Teachings',
    'k.magicSystem': 'Martial Art',
    'kp.magicSystem': 'Martial Arts',
    'k.technology': 'Craft',
    'kp.technology': 'Crafts',
    'k.concept': 'Principle',
    'kp.concept': 'Principles',
    'k.loreDocument': 'Scroll',
    'kp.loreDocument': 'Scrolls',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Undertaking',
    'kp.quest': 'Undertakings',
    'k.session': 'Chapter',
    'kp.session': 'Chapters',
    't:Spell': 'Technique',
    't:Spells': 'Techniques',
    't:School': 'Style',
    't:Casting Time': 'Stance Time',
    't:Components': 'Qi Cost',
    't:Legendary Actions': 'Ultimate Techniques',
    't:Class / Profession': 'Path',
    't:Magic Items': 'Treasures',
    't:Race / Ancestry': 'Bloodline',
    't:Source of Power': 'Qi Source',
    't:Rules & Limits': 'Precepts & Limits',
    't:Abilities & Magic': 'Martial Arts & Qi',
    't:Challenge Rating': 'Cultivation Rank',
    't:Currency': 'Taels',
    't:Headquarters': 'Sect Seat',
    't:Title / Epithet': 'Martial Title',
  },
  'ru': {
    'name': 'Уся',
    'hint': 'Цзянху клинков и ци: Секты, Боевые искусства, Свитки',
    'k.character': 'Герой',
    'kp.character': 'Герои и злодеи',
    'k.location': 'Место',
    'kp.location': 'Реки и озёра',
    'k.item': 'Сокровище',
    'kp.item': 'Сокровища',
    'k.creature': 'Духовный зверь',
    'kp.creature': 'Духовные звери',
    'k.faction': 'Секта',
    'kp.faction': 'Секты и кланы',
    'k.event': 'Происшествие',
    'kp.event': 'Происшествия',
    'k.era': 'Династия',
    'kp.era': 'Династии',
    'k.religion': 'Учение',
    'kp.religion': 'Учения',
    'k.magicSystem': 'Боевое искусство',
    'kp.magicSystem': 'Боевые искусства',
    'k.technology': 'Ремесло',
    'kp.technology': 'Ремёсла',
    'k.concept': 'Принцип',
    'kp.concept': 'Принципы',
    'k.loreDocument': 'Свиток',
    'kp.loreDocument': 'Свитки',
    'k.campaign': 'Сага',
    'kp.campaign': 'Саги',
    'k.quest': 'Деяние',
    'kp.quest': 'Деяния',
    'k.session': 'Глава',
    'kp.session': 'Главы',
    't:Spell': 'Техника',
    't:Spells': 'Техники',
    't:School': 'Стиль',
    't:Casting Time': 'Время стойки',
    't:Components': 'Затраты ци',
    't:Legendary Actions': 'Высшие техники',
    't:Class / Profession': 'Путь',
    't:Magic Items': 'Сокровища',
    't:Race / Ancestry': 'Родословная',
    't:Source of Power': 'Источник ци',
    't:Rules & Limits': 'Заветы и пределы',
    't:Abilities & Magic': 'Боевые искусства и ци',
    't:Challenge Rating': 'Ступень культивации',
    't:Currency': 'Ляны',
    't:Headquarters': 'Обитель секты',
    't:Title / Epithet': 'Прозвище',
  },
  'de': {
    'name': 'Wuxia',
    'hint': 'Ein Jianghu der Klingen und des Qi: Sekten, Kampfkünste, Schriftrollen',
    'k.character': 'Held',
    'kp.character': 'Helden & Schurken',
    'k.location': 'Ort',
    'kp.location': 'Flüsse & Seen',
    'k.item': 'Schatz',
    'kp.item': 'Schätze',
    'k.creature': 'Geistbestie',
    'kp.creature': 'Geistbestien',
    'k.faction': 'Sekte',
    'kp.faction': 'Sekten & Clans',
    'k.event': 'Vorfall',
    'kp.event': 'Vorfälle',
    'k.era': 'Dynastie',
    'kp.era': 'Dynastien',
    'k.religion': 'Lehre',
    'kp.religion': 'Lehren',
    'k.magicSystem': 'Kampfkunst',
    'kp.magicSystem': 'Kampfkünste',
    'k.technology': 'Handwerk',
    'kp.technology': 'Handwerke',
    'k.concept': 'Prinzip',
    'kp.concept': 'Prinzipien',
    'k.loreDocument': 'Schriftrolle',
    'kp.loreDocument': 'Schriftrollen',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Unterfangen',
    'kp.quest': 'Unterfangen',
    'k.session': 'Kapitel',
    'kp.session': 'Kapitel',
    't:Spell': 'Technik',
    't:Spells': 'Techniken',
    't:School': 'Stil',
    't:Casting Time': 'Haltungszeit',
    't:Components': 'Qi-Kosten',
    't:Legendary Actions': 'Meistertechniken',
    't:Class / Profession': 'Pfad',
    't:Magic Items': 'Schätze',
    't:Race / Ancestry': 'Blutlinie',
    't:Source of Power': 'Qi-Quelle',
    't:Rules & Limits': 'Gebote & Grenzen',
    't:Abilities & Magic': 'Kampfkunst & Qi',
    't:Challenge Rating': 'Kultivationsstufe',
    't:Currency': 'Tael',
    't:Headquarters': 'Sektensitz',
    't:Title / Epithet': 'Beiname',
  },
  'fr': {
    'name': 'Wuxia',
    'hint': 'Un jianghu de lames et de qi : Sectes, Arts martiaux, Rouleaux',
    'k.character': 'Héros',
    'kp.character': 'Héros et scélérats',
    'k.location': 'Lieu',
    'kp.location': 'Fleuves et lacs',
    'k.item': 'Trésor',
    'kp.item': 'Trésors',
    'k.creature': 'Bête spirituelle',
    'kp.creature': 'Bêtes spirituelles',
    'k.faction': 'Secte',
    'kp.faction': 'Sectes et clans',
    'k.event': 'Incident',
    'kp.event': 'Incidents',
    'k.era': 'Dynastie',
    'kp.era': 'Dynasties',
    'k.religion': 'Enseignement',
    'kp.religion': 'Enseignements',
    'k.magicSystem': 'Art martial',
    'kp.magicSystem': 'Arts martiaux',
    'k.technology': 'Savoir-faire',
    'kp.technology': 'Savoir-faire',
    'k.concept': 'Principe',
    'kp.concept': 'Principes',
    'k.loreDocument': 'Rouleau',
    'kp.loreDocument': 'Rouleaux',
    'k.campaign': 'Saga',
    'kp.campaign': 'Sagas',
    'k.quest': 'Entreprise',
    'kp.quest': 'Entreprises',
    'k.session': 'Chapitre',
    'kp.session': 'Chapitres',
    't:Spell': 'Technique',
    't:Spells': 'Techniques',
    't:School': 'Style',
    't:Casting Time': 'Temps de posture',
    't:Components': 'Coût en qi',
    't:Legendary Actions': 'Techniques ultimes',
    't:Class / Profession': 'Voie',
    't:Magic Items': 'Trésors',
    't:Race / Ancestry': 'Lignée',
    't:Source of Power': 'Source de qi',
    't:Rules & Limits': 'Préceptes et limites',
    't:Abilities & Magic': 'Arts martiaux et qi',
    't:Challenge Rating': 'Rang de cultivation',
    't:Currency': 'Taëls',
    't:Headquarters': 'Siège de la secte',
    't:Title / Epithet': 'Surnom martial',
  },
  'zh': {
    'name': '武侠',
    'hint': '刀光剑影的江湖：门派、武功、秘籍',
    'k.character': '侠客',
    'kp.character': '正邪人物',
    'k.location': '地点',
    'kp.location': '江湖',
    'k.item': '宝物',
    'kp.item': '宝物',
    'k.creature': '灵兽',
    'kp.creature': '灵兽',
    'k.faction': '门派',
    'kp.faction': '门派与世家',
    'k.event': '事件',
    'kp.event': '事件',
    'k.era': '朝代',
    'kp.era': '朝代',
    'k.religion': '教义',
    'kp.religion': '教义',
    'k.magicSystem': '武功',
    'kp.magicSystem': '武学',
    'k.technology': '技艺',
    'kp.technology': '技艺',
    'k.concept': '法则',
    'kp.concept': '法则',
    'k.loreDocument': '秘籍',
    'kp.loreDocument': '秘籍',
    'k.campaign': '传奇',
    'kp.campaign': '传奇',
    'k.quest': '历练',
    'kp.quest': '历练',
    'k.session': '回',
    'kp.session': '章回',
    't:Spell': '招式',
    't:Spells': '招式',
    't:School': '流派',
    't:Casting Time': '起势时间',
    't:Components': '内力消耗',
    't:Legendary Actions': '绝招',
    't:Class / Profession': '道途',
    't:Magic Items': '宝物',
    't:Race / Ancestry': '血脉',
    't:Source of Power': '内力来源',
    't:Rules & Limits': '戒律与局限',
    't:Abilities & Magic': '武功与内力',
    't:Challenge Rating': '境界',
    't:Currency': '银两',
    't:Headquarters': '山门',
    't:Title / Epithet': '江湖名号',
  },
};
