import '../../models/world.dart';
import 'table_library.dart';

const _s = WorldStyle.cosmicHorror;

const cosmicHorrorTables = <LibraryTable>[
  LibraryTable(
    localId: 'strange_encounters',
    style: _s,
    folder: LibraryFolder.encounters,
    formula: '1d10',
    name: Tx('Strange Encounters', 'Странные встречи', 'Seltsame Begegnungen',
        'Rencontres étranges', '诡异遭遇'),
    description: Tx(
      'People and things investigators run into in fog-bound towns and dusty archives.',
      'Люди и явления, с которыми сыщики сталкиваются в туманных городках и пыльных архивах.',
      'Menschen und Dinge, denen Ermittler in nebligen Städtchen und staubigen Archiven begegnen.',
      'Les gens et les choses que les enquêteurs croisent dans les bourgades brumeuses et les archives poussiéreuses.',
      '调查员在雾锁小镇和积尘档案馆里撞见的人与事。',
    ),
    rows: [
      LibraryRow(Tx(
        'A fisherman with too many joints in his fingers offers to row you across the bay.',
        'Рыбак со слишком большим количеством суставов в пальцах предлагает перевезти вас через залив.',
        'Ein Fischer mit zu vielen Fingergelenken bietet an, euch über die Bucht zu rudern.',
        'Un pêcheur aux doigts trop articulés propose de vous faire traverser la baie.',
        '一个手指关节多得出奇的渔夫，提出划船送你过海湾。',
      )),
      LibraryRow(Tx(
        'A librarian who insists the book you want was never written, then slips you a note.',
        'Библиотекарь уверяет, что нужная вам книга никогда не была написана, — и тайком передаёт записку.',
        'Eine Bibliothekarin beteuert, das gesuchte Buch sei nie geschrieben worden, und steckt euch einen Zettel zu.',
        'Une bibliothécaire affirme que le livre recherché n\'a jamais été écrit, puis vous glisse un mot.',
        '图书管理员坚称你要的书从未被写出来，随后却偷偷塞给你一张纸条。',
      )),
      LibraryRow(Tx(
        'A professor from Miskatonia, feverish, clutching a satchel. [[@quirks]]',
        'Профессор из Мискатонии в лихорадке прижимает к груди сумку. [[@quirks]]',
        'Ein fiebriger Professor aus Miskatonia, eine Tasche umklammernd. [[@quirks]]',
        'Un professeur de Miskatonia, fiévreux, serrant une sacoche. [[@quirks]]',
        '一位来自米斯卡托尼亚的教授，发着高烧，死死抱着一只挎包。[[@quirks]]',
      )),
      LibraryRow(Tx(
        '{1d4+2} cultists in ordinary clothes, humming the same tune on a street corner.',
        '{1d4+2} сектантов в обычной одежде напевают один и тот же мотив на углу.',
        '{1d4+2} Kultisten in Alltagskleidung summen an einer Straßenecke dieselbe Melodie.',
        '{1d4+2} cultistes en habits ordinaires fredonnent le même air au coin d\'une rue.',
        '{1d4+2}个衣着普通的邪教徒站在街角，哼着同一段旋律。',
      )),
      LibraryRow(Tx(
        'The fog thickens and carries something with it: [[@signs]]',
        'Туман густеет и приносит с собой нечто: [[@signs]]',
        'Der Nebel wird dichter und bringt etwas mit sich: [[@signs]]',
        'Le brouillard s\'épaissit et charrie quelque chose : [[@signs]]',
        '雾越来越浓，带来了某种东西：[[@signs]]',
      )),
      LibraryRow(Tx(
        'A policeman who knows more than he says and wants you out of town by sundown.',
        'Полицейский знает больше, чем говорит, и хочет, чтобы вы уехали до заката.',
        'Ein Polizist weiß mehr, als er sagt, und will euch vor Sonnenuntergang aus der Stadt haben.',
        'Un policier qui en sait plus qu\'il n\'en dit veut que vous quittiez la ville avant la nuit.',
        '一个知道得比说得多的警察，要你们日落前离开小镇。',
      )),
      LibraryRow(Tx(
        'A stray dog follows you, and its shadow walks a little behind it.',
        'За вами увязывается бродячая собака, а её тень идёт чуть позади.',
        'Ein streunender Hund folgt euch, und sein Schatten läuft ein Stück hinterher.',
        'Un chien errant vous suit, et son ombre marche un peu en retard.',
        '一条流浪狗跟着你，它的影子落后它几步走着。',
      )),
      LibraryRow(Tx(
        'An antiquarian offers {a clay tablet|a bronze key|a map of the sea floor} and wants no money for it.',
        'Антиквар предлагает {глиняную табличку|бронзовый ключ|карту морского дна} и не берёт денег.',
        'Ein Antiquar bietet {eine Tontafel|einen Bronzeschlüssel|eine Karte des Meeresbodens} an und will kein Geld dafür.',
        'Un antiquaire propose {une tablette d\'argile|une clé de bronze|une carte des fonds marins} et n\'en veut pas un sou.',
        '一个古董商拿出{一块泥板|一把青铜钥匙|一张海底地图}，分文不取。',
      )),
      LibraryRow(Tx(
        'The house you are watching has one more window from the outside than from the inside.',
        'У дома, за которым вы следите, снаружи на одно окно больше, чем изнутри.',
        'Das Haus, das ihr beobachtet, hat von außen ein Fenster mehr als von innen.',
        'La maison que vous surveillez a une fenêtre de plus vue de l\'extérieur que de l\'intérieur.',
        '你们监视的那栋房子，从外面数比从里面数多出一扇窗。',
      )),
      LibraryRow(Tx(
        'A survivor of the last expedition, who only repeats one word: "{Below|Awake|Soon}".',
        'Выживший из прошлой экспедиции повторяет лишь одно слово: «{Внизу|Проснулся|Скоро}».',
        'Ein Überlebender der letzten Expedition wiederholt nur ein Wort: „{Unten|Erwacht|Bald}“.',
        'Un survivant de la dernière expédition ne répète qu\'un mot : « {Dessous|Éveillé|Bientôt} ».',
        '上一支探险队的幸存者只会重复一个词：“{下面|醒了|快了}”。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'signs',
    style: _s,
    folder: LibraryFolder.locale,
    formula: '1d20',
    name: Tx('Sanity-Straining Signs', 'Знаки, пугающие рассудок',
        'Zeichen, die den Verstand zermürben', 'Signes qui ébranlent la raison',
        '动摇理智的征兆'),
    description: Tx(
      'Small wrongnesses that tell the investigators the world is thinner here. Rarer results are worse.',
      'Мелкие неправильности, говорящие сыщикам, что мир здесь тоньше. Чем реже результат, тем хуже.',
      'Kleine Unstimmigkeiten, die verraten, dass die Welt hier dünner ist. Seltene Ergebnisse sind schlimmer.',
      'De petites anomalies qui révèlent que le monde est plus mince ici. Les résultats rares sont les pires.',
      '一些细微的不对劲，提示调查员这里的世界更加稀薄。越罕见的结果越糟。',
    ),
    rows: [
      LibraryRow(Tx(
        'Every clock in the building disagrees by exactly {1d12} minutes.',
        'Все часы в здании расходятся ровно на {1d12} минут.',
        'Alle Uhren im Gebäude gehen um genau {1d12} Minuten auseinander.',
        'Toutes les horloges du bâtiment divergent d\'exactement {1d12} minutes.',
        '楼里所有的钟彼此都恰好相差{1d12}分钟。',
      ), weight: 3),
      LibraryRow(Tx(
        'The tide comes in when it should be going out.',
        'Прилив наступает, когда должен быть отлив.',
        'Die Flut kommt, wenn eigentlich Ebbe sein müsste.',
        'La marée monte alors qu\'elle devrait descendre.',
        '本该退潮的时候却涨起了潮。',
      ), weight: 3),
      LibraryRow(Tx(
        'Wet footprints lead from the sea to the church, and none lead back.',
        'Мокрые следы ведут от моря к церкви, и ни одного обратно.',
        'Nasse Fußspuren führen vom Meer zur Kirche, keine zurück.',
        'Des traces de pas mouillées vont de la mer à l\'église, aucune n\'en revient.',
        '湿脚印从海边一路通往教堂，没有一个是往回走的。',
      ), weight: 2),
      LibraryRow(Tx(
        'The stars overhead are almost right. One is missing.',
        'Звёзды над головой почти правильные. Одной не хватает.',
        'Die Sterne am Himmel stehen fast richtig. Einer fehlt.',
        'Les étoiles sont presque à leur place. Il en manque une.',
        '头顶的星辰几乎都在该在的位置，只少了一颗。',
      ), weight: 2),
      LibraryRow(Tx(
        'A photograph develops showing someone standing behind you who was not there.',
        'На проявленной фотографии за вашей спиной стоит кто-то, кого там не было.',
        'Ein entwickeltes Foto zeigt jemanden hinter euch, der nicht da war.',
        'Une photo développée montre derrière vous quelqu\'un qui n\'était pas là.',
        '冲洗出来的照片上，你身后站着一个当时并不在场的人。',
      ), weight: 2),
      LibraryRow(Tx(
        'Everyone in town dreamed the same dream last night: {a drowned city|a door in the sky|a vast eye opening}.',
        'Прошлой ночью всем в городе снился один сон: {затонувший город|дверь в небе|открывающийся огромный глаз}.',
        'Letzte Nacht träumte die ganze Stadt denselben Traum: {eine versunkene Stadt|eine Tür im Himmel|ein riesiges Auge, das sich öffnet}.',
        'Toute la ville a fait le même rêve cette nuit : {une cité engloutie|une porte dans le ciel|un œil immense qui s\'ouvre}.',
        '昨晚全镇人都做了同一个梦：{一座沉没的城市|天空中的一扇门|一只巨眼缓缓睁开}。',
      ), weight: 2),
      LibraryRow(Tx(
        'Geometry fails: a corridor is longer walking back than walking in.',
        'Геометрия ломается: обратно коридор длиннее, чем туда.',
        'Die Geometrie versagt: Der Flur ist auf dem Rückweg länger als auf dem Hinweg.',
        'La géométrie flanche : le couloir est plus long au retour qu\'à l\'aller.',
        '几何失效了：走廊往回走比走进来时更长。',
      ), weight: 2),
      LibraryRow(Tx(
        'Your own handwriting appears in a book printed a century ago.',
        'Ваш собственный почерк обнаруживается в книге, напечатанной век назад.',
        'Eure eigene Handschrift taucht in einem Buch auf, das vor einem Jahrhundert gedruckt wurde.',
        'Votre propre écriture apparaît dans un livre imprimé il y a un siècle.',
        '一本百年前印刷的书里出现了你自己的笔迹。',
      ), weight: 2),
      LibraryRow(Tx(
        'A chorus of voices from the drains, singing in a language with no vowels.',
        'Хор голосов из водостоков поёт на языке без гласных.',
        'Ein Chor aus den Abflüssen singt in einer Sprache ohne Vokale.',
        'Un chœur de voix monte des égouts, chantant dans une langue sans voyelles.',
        '下水道里传来合唱声，唱的是一种没有元音的语言。',
      ), weight: 1),
      LibraryRow(Tx(
        'For one heartbeat you see the true shape of the sky, and it sees you.',
        'На один удар сердца вы видите истинную форму неба — и оно видит вас.',
        'Einen Herzschlag lang seht ihr die wahre Gestalt des Himmels, und er sieht euch.',
        'L\'espace d\'un battement de cœur, vous voyez la vraie forme du ciel, et il vous voit.',
        '在一次心跳的瞬间，你看见了天空真正的形状——而它也看见了你。',
      ), weight: 1),
    ],
  ),
  LibraryTable(
    localId: 'leads',
    style: _s,
    folder: LibraryFolder.rumors,
    formula: '1d10',
    name: Tx('Whispered Leads', 'Шёпотом о зацепках', 'Geflüsterte Spuren',
        'Pistes chuchotées', '低语线索'),
    description: Tx(
      'Tips, clippings and hearsay that pull investigators deeper.',
      'Наводки, газетные вырезки и слухи, затягивающие сыщиков всё глубже.',
      'Hinweise, Zeitungsausschnitte und Hörensagen, die Ermittler tiefer hineinziehen.',
      'Tuyaux, coupures de presse et ouï-dire qui entraînent les enquêteurs plus loin.',
      '把调查员越拉越深的线报、剪报和传言。',
    ),
    rows: [
      LibraryRow(Tx(
        'A newspaper notice: an estate sale at the Whateley house, everything must go.',
        'Объявление в газете: распродажа имущества в доме Уэйтли, всё должно уйти.',
        'Eine Zeitungsanzeige: Nachlassverkauf im Haus Whateley, alles muss raus.',
        'Une annonce : vente de succession à la maison Whateley, tout doit partir.',
        '报上一则启事：惠特利宅邸遗产拍卖，全部清仓。',
      )),
      LibraryRow(Tx(
        'The asylum lost a patient who draws perfect maps of places no one has visited.',
        'Из лечебницы пропал пациент, рисующий точные карты мест, где никто не бывал.',
        'Aus der Anstalt ist ein Patient verschwunden, der perfekte Karten nie besuchter Orte zeichnet.',
        'L\'asile a perdu un patient qui dessine des cartes parfaites de lieux où personne n\'est allé.',
        '疯人院走失了一个病人，他能画出无人到过之地的精确地图。',
      )),
      LibraryRow(Tx(
        'A ship came into harbor with no crew and a hold full of [[@finds]]',
        'В гавань вошёл корабль без экипажа, а в трюме: [[@finds]]',
        'Ein Schiff lief ohne Besatzung in den Hafen ein, der Laderaum voller: [[@finds]]',
        'Un navire est entré au port sans équipage, la cale pleine de : [[@finds]]',
        '一艘船驶入港口，船上没有船员，货舱里满是：[[@finds]]',
      )),
      LibraryRow(Tx(
        'A university grant pays {1d6*100} dollars for "unusual folklore" from the coast.',
        'Университетский грант платит {1d6*100} долларов за «необычный фольклор» с побережья.',
        'Ein Universitätsstipendium zahlt {1d6*100} Dollar für „ungewöhnliche Volkskunde“ von der Küste.',
        'Une bourse universitaire paie {1d6*100} dollars pour du « folklore inhabituel » de la côte.',
        '一项大学资助愿出{1d6*100}美元，收集沿海的“奇特民俗”。',
      )),
      LibraryRow(Tx(
        'The lighthouse keeper stopped lighting the lamp. He says it attracts them.',
        'Смотритель маяка перестал зажигать огонь. Говорит, он их привлекает.',
        'Der Leuchtturmwärter zündet die Lampe nicht mehr an. Er sagt, sie lockt sie an.',
        'Le gardien du phare n\'allume plus la lampe. Il dit qu\'elle les attire.',
        '灯塔看守不再点灯了。他说灯光会把“它们”引来。',
      )),
      LibraryRow(Tx(
        'An old sailor in the tavern will talk for whiskey. Walk home and meet [[@strange_encounters]]',
        'Старый моряк в таверне всё расскажет за виски. По дороге домой: [[@strange_encounters]]',
        'Ein alter Seemann in der Kneipe redet für Whiskey. Auf dem Heimweg: [[@strange_encounters]]',
        'Un vieux marin de la taverne parle contre du whisky. En rentrant : [[@strange_encounters]]',
        '酒馆里的老水手给杯威士忌就肯开口。回家路上：[[@strange_encounters]]',
      )),
      LibraryRow(Tx(
        'Radio operators hear a {counting voice|slow heartbeat|choir} on a dead frequency.',
        'Радисты слышат на мёртвой частоте {голос, ведущий счёт|медленное сердцебиение|хор}.',
        'Funker hören auf einer toten Frequenz {eine zählende Stimme|einen langsamen Herzschlag|einen Chor}.',
        'Des radios captent sur une fréquence morte {une voix qui compte|un cœur qui bat lentement|un chœur}.',
        '无线电员在一个死频率上听到了{报数的声音|缓慢的心跳|合唱}。',
      )),
      LibraryRow(Tx(
        'The quarry workers dug into a chamber with carvings older than the hills.',
        'Рабочие карьера вскрыли камеру с резьбой древнее холмов.',
        'Die Steinbrucharbeiter stießen auf eine Kammer mit Ritzungen, älter als die Hügel.',
        'Les ouvriers de la carrière ont percé une chambre aux gravures plus vieilles que les collines.',
        '采石工挖进了一间石室，里面的雕刻比这些山丘还要古老。',
      )),
      LibraryRow(Tx(
        'A missing heiress wrote to her sister last week, from the bottom of the lake.',
        'Пропавшая наследница на прошлой неделе написала сестре — со дна озера.',
        'Eine vermisste Erbin schrieb letzte Woche ihrer Schwester, vom Grund des Sees.',
        'Une héritière disparue a écrit à sa sœur la semaine dernière, du fond du lac.',
        '失踪的女继承人上周给姐姐写了信——寄自湖底。',
      )),
      LibraryRow(Tx(
        'Three scholars bought the same forbidden book this month. Two are dead.',
        'В этом месяце трое учёных купили одну и ту же запретную книгу. Двое мертвы.',
        'Diesen Monat kauften drei Gelehrte dasselbe verbotene Buch. Zwei sind tot.',
        'Ce mois-ci, trois érudits ont acheté le même livre interdit. Deux sont morts.',
        '这个月有三位学者买了同一本禁书，其中两人已经死了。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'finds',
    style: _s,
    folder: LibraryFolder.loot,
    formula: '1d20',
    name: Tx('Archive Finds', 'Находки в архивах', 'Archivfunde',
        'Trouvailles d\'archives', '档案发现'),
    description: Tx(
      'Documents and objects that help the investigation, at a price.',
      'Документы и предметы, помогающие расследованию, — за свою цену.',
      'Dokumente und Gegenstände, die der Ermittlung helfen, zu einem Preis.',
      'Documents et objets qui aident l\'enquête, à un certain prix.',
      '对调查有帮助的文件和物件——但要付出代价。',
    ),
    rows: [
      LibraryRow(Tx(
        'A bundle of letters tied with fishing line, {2d6} in all.',
        'Связка писем, перевязанная леской, — всего {2d6}.',
        'Ein Bündel Briefe, mit Angelschnur verschnürt, {2d6} Stück.',
        'Une liasse de lettres nouée de fil de pêche, {2d6} en tout.',
        '一捆用钓鱼线扎起来的信，共{2d6}封。',
      ), weight: 3),
      LibraryRow(Tx(
        'A property map with one lot circled in red ink and the note "not ours".',
        'Кадастровая карта: один участок обведён красным, приписка — «не наш».',
        'Ein Grundstücksplan, eine Parzelle rot umkreist, daneben „nicht unseres“.',
        'Un plan cadastral, une parcelle entourée de rouge et la mention « pas à nous ».',
        '一张地产图，一块地用红墨水圈出，旁注“不是我们的”。',
      ), weight: 3),
      LibraryRow(Tx(
        'A torn page of a ritual, missing its {first|middle|final} verse.',
        'Вырванная страница ритуала без {первой|средней|последней} строфы.',
        'Eine ausgerissene Ritualseite, der {erste|mittlere|letzte} Vers fehlt.',
        'Une page de rituel déchirée : il manque la strophe {du début|du milieu|de la fin}.',
        '一页撕下来的仪式文稿，缺了{开头|中间|最后}一节。',
      ), weight: 2),
      LibraryRow(Tx(
        'A wax cylinder recording of a lecture that ends in screaming.',
        'Запись лекции на восковом валике, которая заканчивается криком.',
        'Eine Wachswalzenaufnahme eines Vortrags, der in Schreien endet.',
        'Un cylindre de cire enregistrant une conférence qui finit en hurlements.',
        '一段蜡筒录音，是一场以尖叫收尾的讲座。',
      ), weight: 2),
      LibraryRow(Tx(
        'A ledger showing payments to the town council from "the Order".',
        'Гроссбух с выплатами городскому совету от «Ордена».',
        'Ein Kassenbuch mit Zahlungen „des Ordens“ an den Stadtrat.',
        'Un registre de paiements de « l\'Ordre » au conseil municipal.',
        '一本账簿，记录着“教团”付给镇议会的款项。',
      ), weight: 2),
      LibraryRow(Tx(
        'An amulet of greenish stone, cold even in the sun.',
        'Амулет из зеленоватого камня, холодный даже на солнце.',
        'Ein Amulett aus grünlichem Stein, selbst in der Sonne kalt.',
        'Une amulette de pierre verdâtre, froide même au soleil.',
        '一枚淡绿色石头护符，即使晒在太阳下也冰冷。',
      ), weight: 2),
      LibraryRow(Tx(
        'A photograph of your own house, taken from inside a room you do not have.',
        'Фотография вашего дома, снятая из комнаты, которой у вас нет.',
        'Ein Foto eures Hauses, aufgenommen aus einem Zimmer, das ihr nicht habt.',
        'Une photo de votre maison prise depuis une pièce que vous n\'avez pas.',
        '一张你家房子的照片，拍摄地点是一间你家并不存在的房间。',
      ), weight: 2),
      LibraryRow(Tx(
        'A revolver with {1d6} silver bullets and the initials of a dead detective.',
        'Револьвер с {1d6} серебряными пулями и инициалами погибшего детектива.',
        'Ein Revolver mit {1d6} Silberkugeln und den Initialen eines toten Detektivs.',
        'Un revolver avec {1d6} balles d\'argent et les initiales d\'un détective mort.',
        '一把装着{1d6}发银子弹的左轮，刻着一位已故侦探的姓名缩写。',
      ), weight: 2),
      LibraryRow(Tx(
        'A diary in shorthand. The last pages are in a hand that grows less human.',
        'Дневник стенографией. Последние страницы написаны всё менее человеческой рукой.',
        'Ein Tagebuch in Kurzschrift. Die letzten Seiten stammen von einer immer weniger menschlichen Hand.',
        'Un journal en sténo. Les dernières pages sont d\'une main de moins en moins humaine.',
        '一本速记日记，最后几页的笔迹越来越不像人写的。',
      ), weight: 1),
      LibraryRow(Tx(
        'A key that fits every door in the house, including one that was bricked up.',
        'Ключ, подходящий ко всем дверям дома, включая замурованную.',
        'Ein Schlüssel, der in jede Tür des Hauses passt, auch in eine zugemauerte.',
        'Une clé qui ouvre toutes les portes de la maison, y compris une porte murée.',
        '一把能打开房子里所有门的钥匙，包括那扇被砌死的门。',
      ), weight: 1),
    ],
  ),
  LibraryTable(
    localId: 'quirks',
    style: _s,
    folder: LibraryFolder.people,
    name: Tx('Witness Quirks', 'Причуды свидетелей', 'Marotten von Zeugen',
        'Manies des témoins', '证人怪癖'),
    description: Tx(
      'Details for townsfolk, scholars and witnesses who have seen a little too much.',
      'Детали для горожан, учёных и свидетелей, видевших чуть больше, чем нужно.',
      'Details für Städter, Gelehrte und Zeugen, die ein wenig zu viel gesehen haben.',
      'Des détails pour les citadins, érudits et témoins qui en ont vu un peu trop.',
      '给见识稍微多了些的镇民、学者和证人添点细节。',
    ),
    rows: [
      LibraryRow(Tx(
        'Keeps every light in the house on, day and night.',
        'Не выключает свет в доме ни днём, ни ночью.',
        'Lässt jedes Licht im Haus brennen, Tag und Nacht.',
        'Laisse toutes les lumières allumées, jour et nuit.',
        '家里的灯无论白天黑夜都开着。',
      ), weight: 2),
      LibraryRow(Tx(
        'Answers questions a moment before they are asked.',
        'Отвечает на вопросы за миг до того, как их зададут.',
        'Beantwortet Fragen einen Moment, bevor sie gestellt werden.',
        'Répond aux questions un instant avant qu\'on les pose.',
        '总在别人问出问题的前一刻就作答。',
      )),
      LibraryRow(Tx(
        'Smells faintly of {brine|ozone|old paper} no matter how often they wash.',
        'Сколько ни мойся, от него слабо пахнет {рассолом|озоном|старой бумагой}.',
        'Riecht schwach nach {Salzlake|Ozon|altem Papier}, egal wie oft gewaschen.',
        'Sent légèrement {la saumure|l\'ozone|le vieux papier}, même après s\'être lavé.',
        '不管洗多少次，身上总有淡淡的{咸水|臭氧|旧纸}味。',
      )),
      LibraryRow(Tx(
        'Hums to drown out a sound only they can hear.',
        'Напевает, чтобы заглушить звук, который слышит только он.',
        'Summt, um ein Geräusch zu übertönen, das nur er hört.',
        'Fredonne pour couvrir un son que lui seul entend.',
        '用哼歌来盖过只有自己听得见的声音。',
      ), weight: 2),
      LibraryRow(Tx(
        'Carries a notebook of dreams, dated and numbered.',
        'Носит блокнот со снами — с датами и номерами.',
        'Trägt ein Notizbuch voller Träume, datiert und nummeriert.',
        'Tient un carnet de rêves, datés et numérotés.',
        '随身带着一本记梦的笔记，每条都标了日期和编号。',
      )),
      LibraryRow(Tx(
        'Will not look at the sea, not even in a painting.',
        'Не смотрит на море — даже на картине.',
        'Schaut nie aufs Meer, nicht einmal auf einem Gemälde.',
        'Refuse de regarder la mer, même en peinture.',
        '不肯看海，连画上的也不看。',
      )),
      LibraryRow(Tx(
        'Laughs at the wrong moments and apologizes in Latin.',
        'Смеётся невпопад и извиняется на латыни.',
        'Lacht an den falschen Stellen und entschuldigt sich auf Latein.',
        'Rit au mauvais moment et s\'excuse en latin.',
        '总在不该笑的时候笑，然后用拉丁语道歉。',
      )),
      LibraryRow(Tx(
        'Counts the exits of every room out loud.',
        'Вслух пересчитывает выходы в каждой комнате.',
        'Zählt in jedem Raum laut die Ausgänge.',
        'Compte à voix haute les sorties de chaque pièce.',
        '进每个房间都要大声数一遍出口。',
      )),
      LibraryRow(Tx(
        'Has webbed skin between two fingers and wears gloves in summer.',
        'Между двумя пальцами перепонка; носит перчатки даже летом.',
        'Hat Schwimmhäute zwischen zwei Fingern und trägt im Sommer Handschuhe.',
        'A la peau palmée entre deux doigts et porte des gants en été.',
        '两根手指间长着蹼，夏天也戴着手套。',
      )),
      LibraryRow(Tx(
        'Is sure they met you before, and describes a meeting that has not happened yet.',
        'Уверен, что встречал вас, и описывает встречу, которой ещё не было.',
        'Ist sicher, euch schon getroffen zu haben, und beschreibt ein Treffen, das noch nicht stattfand.',
        'Est certain de vous avoir déjà vu et décrit une rencontre qui n\'a pas encore eu lieu.',
        '确信以前见过你，并描述了一次尚未发生的会面。',
      )),
    ],
  ),
];
