import '../../models/world.dart';
import 'table_library.dart';

const _s = WorldStyle.cyberpunk;

const cyberpunkTables = <LibraryTable>[
  LibraryTable(
    localId: 'street_encounters',
    style: _s,
    folder: LibraryFolder.encounters,
    formula: '2d6',
    name: Tx('Street Encounters', 'Уличные встречи', 'Straßenbegegnungen',
        'Rencontres de rue', '街头遭遇'),
    description: Tx(
      'Who crosses your path in the neon canyons after midnight.',
      'Кто попадается на пути в неоновых ущельях после полуночи.',
      'Wer euch nach Mitternacht in den Neonschluchten über den Weg läuft.',
      'Qui croise votre route dans les canyons de néon après minuit.',
      '午夜后的霓虹峡谷里，谁会挡在你的路上。',
    ),
    rows: [
      LibraryRow(Tx(
        'A corporate kill team in matte armor, hunting someone who looks a lot like you.',
        'Корпоративная группа зачистки в матовой броне охотится на кого-то очень похожего на вас.',
        'Ein Konzern-Killerteam in matter Panzerung jagt jemanden, der euch verdächtig ähnlich sieht.',
        'Une équipe de nettoyage corpo en armure mate traque quelqu\'un qui vous ressemble beaucoup.',
        '一支身穿哑光装甲的公司清道夫小队，正在追杀一个和你长得很像的人。',
      )),
      LibraryRow(Tx(
        '{1d6+2} gangers on chromed bikes want a "road tax". Their leader: [[@quirks]]',
        '{1d6+2} бандитов на хромированных байках требуют «дорожный налог». Их главарь: [[@quirks]]',
        '{1d6+2} Gangmitglieder auf verchromten Bikes wollen „Wegezoll“. Ihr Boss: [[@quirks]]',
        '{1d6+2} gangers sur des motos chromées réclament une « taxe de passage ». Leur chef : [[@quirks]]',
        '{1d6+2}个骑着镀铬摩托的帮派分子要收“过路税”。头目：[[@quirks]]',
      )),
      LibraryRow(Tx(
        'A street doc stitching a courier in an alley begs you to hold the light.',
        'Уличный хирург латает курьера в переулке и умоляет подержать фонарь.',
        'Ein Straßendoc flickt in einer Gasse einen Kurier zusammen und bittet euch, die Lampe zu halten.',
        'Un charcudoc recoud un coursier dans une ruelle et vous supplie de tenir la lampe.',
        '一个街头医生在小巷里给快递员缝合伤口，恳求你帮忙打灯。',
      )),
      LibraryRow(Tx(
        'Police drones sweep the block; everyone without a clean ID scatters.',
        'Полицейские дроны прочёсывают квартал; все, у кого нечистый ID, разбегаются.',
        'Polizeidrohnen kämmen den Block durch; wer keine saubere ID hat, verschwindet.',
        'Des drones de police ratissent le bloc ; tous ceux qui n\'ont pas d\'ID propre s\'éparpillent.',
        '警用无人机扫荡街区，身份不干净的人一哄而散。',
      )),
      LibraryRow(Tx(
        'A vending machine glitches and spits out [[@loot]]',
        'Торговый автомат глючит и выплёвывает: [[@loot]]',
        'Ein Verkaufsautomat spinnt und spuckt aus: [[@loot]]',
        'Un distributeur bugue et recrache : [[@loot]]',
        '一台自动售货机出了故障，吐出了：[[@loot]]',
      )),
      LibraryRow(Tx(
        'Rain, holo-ads and a crowd. [[@complications]]',
        'Дождь, голореклама и толпа. [[@complications]]',
        'Regen, Holowerbung und Gedränge. [[@complications]]',
        'Pluie, holo-pubs et foule. [[@complications]]',
        '雨幕、全息广告和人潮。[[@complications]]',
      )),
      LibraryRow(Tx(
        'A kid with a cyberdeck twice her size offers to sell you a password.',
        'Девчонка с кибердекой вдвое больше неё предлагает продать пароль.',
        'Ein Kind mit einem Cyberdeck doppelt so groß wie es selbst bietet euch ein Passwort an.',
        'Une gamine avec un cyberdeck deux fois plus grand qu\'elle propose de vous vendre un mot de passe.',
        '一个抱着比自己还大一倍的赛博终端的小女孩，想卖给你一个密码。',
      )),
      LibraryRow(Tx(
        'A preacher of the {Machine God|Clean Flesh|Last Signal} hands out stickers and warnings.',
        'Проповедник {Бога-Машины|Чистой Плоти|Последнего Сигнала} раздаёт наклейки и предостережения.',
        'Ein Prediger {des Maschinengottes|des Reinen Fleisches|des Letzten Signals} verteilt Aufkleber und Warnungen.',
        'Un prêcheur {du Dieu-Machine|de la Chair Pure|du Dernier Signal} distribue autocollants et avertissements.',
        '一个{机械神|纯净血肉|最后信号}的传道者在发贴纸和警告。',
      )),
      LibraryRow(Tx(
        'A cyberpsycho, {1d6} limbs of military chrome, screaming at a noodle stand.',
        'Киберпсих с {1d6} военными хромированными конечностями орёт на лапшичную.',
        'Ein Cyberpsycho mit {1d6} Militär-Chromgliedern brüllt einen Nudelstand an.',
        'Un cyberpsycho aux {1d6} membres de chrome militaire hurle sur un stand de nouilles.',
        '一个装着{1d6}条军用义肢的赛博疯子，正对着面摊尖叫。',
      )),
      LibraryRow(Tx(
        'An old fixer recognizes you and wants to talk about a job. [[@quirks]]',
        'Старый фиксер узнаёт вас и хочет обсудить работу. [[@quirks]]',
        'Ein alter Fixer erkennt euch und will über einen Job reden. [[@quirks]]',
        'Un vieux fixer vous reconnaît et veut parler affaires. [[@quirks]]',
        '一个老中间人认出了你，想谈一单活。[[@quirks]]',
      )),
      LibraryRow(Tx(
        'An armored limousine stops. The window lowers. Nobody is inside.',
        'Бронированный лимузин останавливается. Стекло опускается. Внутри никого.',
        'Eine gepanzerte Limousine hält. Das Fenster fährt herunter. Niemand sitzt darin.',
        'Une limousine blindée s\'arrête. La vitre descend. Il n\'y a personne.',
        '一辆装甲豪车停下，车窗降下——里面空无一人。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'corp_rumors',
    style: _s,
    folder: LibraryFolder.rumors,
    formula: '1d10',
    name: Tx('Corp Rumors', 'Корпоративные слухи', 'Konzerngerüchte',
        'Rumeurs corpo', '公司传闻'),
    description: Tx(
      'Whispers from the arcologies, leaked on the net or sold in bars.',
      'Шёпот из аркологий — утёкший в сеть или проданный в баре.',
      'Geflüster aus den Arkologien, im Netz geleakt oder in Bars verkauft.',
      'Des murmures des arcologies, fuités sur le réseau ou vendus dans les bars.',
      '来自巨构建筑的低语，或在网络上泄露，或在酒吧里出售。',
    ),
    rows: [
      LibraryRow(Tx(
        'A board member died last week, but still sends memos every morning.',
        'Член совета директоров умер на прошлой неделе, но по-прежнему рассылает служебки каждое утро.',
        'Ein Vorstandsmitglied starb letzte Woche, schickt aber weiter jeden Morgen Memos.',
        'Un membre du conseil est mort la semaine dernière, mais il envoie toujours des mémos chaque matin.',
        '一名董事上周死了，可每天早上仍在发备忘录。',
      )),
      LibraryRow(Tx(
        'The water utility is testing a mood additive in the lower districts.',
        'Водоканал испытывает добавку для настроения в нижних районах.',
        'Der Wasserversorger testet in den unteren Bezirken einen Stimmungszusatz.',
        'La compagnie des eaux teste un additif d\'humeur dans les quartiers bas.',
        '供水公司正在下城区测试一种情绪添加剂。',
      )),
      LibraryRow(Tx(
        'Two megacorps are about to merge; their security teams have not been told.',
        'Две мегакорпорации вот-вот сольются; их службы безопасности об этом не знают.',
        'Zwei Megakonzerne fusionieren bald; ihre Sicherheitsteams wissen nichts davon.',
        'Deux mégacorpos vont fusionner ; leurs équipes de sécurité n\'ont pas été prévenues.',
        '两家巨型企业即将合并，它们的安保部队还蒙在鼓里。',
      )),
      LibraryRow(Tx(
        'A prototype cyberarm walked out of a lab on its own. Reward: {1d6*1000} eddies.',
        'Прототип кибер-руки сам ушёл из лаборатории. Награда: {1d6*1000} эдди.',
        'Ein Cyberarm-Prototyp ist allein aus dem Labor spaziert. Belohnung: {1d6*1000} Eddies.',
        'Un prototype de cyberbras est sorti seul du labo. Récompense : {1d6*1000} eddies.',
        '一条原型义臂自己从实验室里“走”了出去。悬赏：{1d6*1000}欧元币。',
      )),
      LibraryRow(Tx(
        'The orbital shuttle crash was no accident: the black box is for sale.',
        'Крушение орбитального челнока не было случайностью: чёрный ящик продаётся.',
        'Der Absturz der Orbitalfähre war kein Unfall: die Blackbox steht zum Verkauf.',
        'Le crash de la navette orbitale n\'était pas un accident : la boîte noire est à vendre.',
        '轨道穿梭机坠毁并非意外：黑匣子正在出售。',
      )),
      LibraryRow(Tx(
        'An AI in the stock exchange is buying up {old apartment blocks|cemetery plots|expired patents}.',
        'ИИ на бирже скупает {старые жилые кварталы|участки на кладбищах|просроченные патенты}.',
        'Eine KI an der Börse kauft {alte Wohnblocks|Friedhofsparzellen|abgelaufene Patente}.',
        'Une IA de la bourse rachète {de vieux immeubles|des concessions funéraires|des brevets expirés}.',
        '证券交易所里的一个AI正在收购{老旧公寓楼|墓地|过期专利}。',
      )),
      LibraryRow(Tx(
        'A gang war is coming to the market district. Expect [[@street_encounters]]',
        'В рыночный квартал идёт война банд. Ждите: [[@street_encounters]]',
        'Ein Bandenkrieg erreicht bald das Marktviertel. Rechnet mit: [[@street_encounters]]',
        'Une guerre des gangs arrive au quartier du marché. Attendez-vous à : [[@street_encounters]]',
        '一场帮派战争即将波及市场区。可能遇到：[[@street_encounters]]',
      )),
      LibraryRow(Tx(
        'A famous idol is really a remote-controlled synthetic. The singer died years ago.',
        'Знаменитый идол на самом деле — управляемый синтетик. Певица умерла много лет назад.',
        'Ein berühmtes Idol ist in Wahrheit ein ferngesteuerter Synth. Die Sängerin starb vor Jahren.',
        'Une idole célèbre est en fait un synthétique télécommandé. La chanteuse est morte il y a des années.',
        '一位当红偶像其实是遥控合成人，真正的歌手几年前就死了。',
      )),
      LibraryRow(Tx(
        'Someone is paying top eddies for memories of the old city before the flood.',
        'Кто-то щедро платит за воспоминания о старом городе до наводнения.',
        'Jemand zahlt Höchstpreise für Erinnerungen an die alte Stadt vor der Flut.',
        'Quelqu\'un paie cher les souvenirs de la vieille ville d\'avant l\'inondation.',
        '有人出高价收购洪水之前老城区的记忆。',
      )),
      LibraryRow(Tx(
        'A clinic on the ninth level installs chrome for free. Nobody comes back for a check-up.',
        'Клиника на девятом уровне ставит хром бесплатно. На осмотр никто не возвращается.',
        'Eine Klinik auf Ebene neun baut Chrom gratis ein. Niemand kommt zur Nachsorge zurück.',
        'Une clinique du neuvième niveau pose du chrome gratuitement. Personne ne revient pour le contrôle.',
        '九层的一家诊所免费装义体。没有一个人回去复诊。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'loot',
    style: _s,
    folder: LibraryFolder.loot,
    formula: '1d20',
    name: Tx('Gear Drops', 'Трофейное железо', 'Beute-Hardware',
        'Matos récupéré', '装备掉落'),
    description: Tx(
      'What falls out of a dead ganger\'s pockets or a cracked courier case.',
      'Что выпадает из карманов мёртвого бандита или вскрытого кейса курьера.',
      'Was aus den Taschen toter Ganger oder einem geknackten Kurierkoffer fällt.',
      'Ce qui tombe des poches d\'un ganger mort ou d\'une mallette de coursier forcée.',
      '死去的帮派分子口袋里、或撬开的快递箱里掉出来的东西。',
    ),
    rows: [
      LibraryRow(Tx(
        'A credstick with {2d6*10} eddies and a thumbprint lock.',
        'Кредстик с {2d6*10} эдди и замком по отпечатку пальца.',
        'Ein Credstick mit {2d6*10} Eddies und Daumenabdruck-Sperre.',
        'Un credstick de {2d6*10} eddies verrouillé par empreinte.',
        '一根存有{2d6*10}欧元币、带指纹锁的信用棒。',
      ), weight: 4),
      LibraryRow(Tx(
        'A {cracked|pristine|stolen} smart pistol, still linked to its former owner.',
        '{Треснувший|Новенький|Краденый} смарт-пистолет, всё ещё привязанный к прежнему владельцу.',
        'Eine {angeknackste|makellose|gestohlene} Smartpistole, noch an den Vorbesitzer gekoppelt.',
        'Un pistolet intelligent {fêlé|impeccable|volé}, toujours lié à son ancien propriétaire.',
        '一把{有裂纹的|崭新的|偷来的}智能手枪，仍与前主人绑定。',
      ), weight: 2),
      LibraryRow(Tx(
        '{1d4} doses of combat stims in an unlabeled injector.',
        '{1d4} доз боевых стимуляторов в инжекторе без маркировки.',
        '{1d4} Dosen Kampfstimulanzien in einem unbeschrifteten Injektor.',
        '{1d4} doses de stimulants de combat dans un injecteur sans étiquette.',
        '无标签注射器里的{1d4}剂战斗兴奋剂。',
      ), weight: 3),
      LibraryRow(Tx(
        'A data shard labeled "DO NOT OPEN" in three languages.',
        'Дата-шард с надписью «НЕ ОТКРЫВАТЬ» на трёх языках.',
        'Ein Datenshard mit der Aufschrift „NICHT ÖFFNEN“ in drei Sprachen.',
        'Un éclat de données marqué « NE PAS OUVRIR » en trois langues.',
        '一块用三种语言标着“请勿打开”的数据碎片。',
      ), weight: 2),
      LibraryRow(Tx(
        'A cybereye, still warm, in a sealed bag.',
        'Киберглаз, ещё тёплый, в запечатанном пакете.',
        'Ein Cyberauge, noch warm, in einem versiegelten Beutel.',
        'Un cyberœil, encore tiède, dans un sachet scellé.',
        '密封袋里的一只义眼，还是温的。',
      ), weight: 2),
      LibraryRow(Tx(
        'A keycard to a corp parking level, valid until midnight.',
        'Ключ-карта от корпоративной парковки, действительна до полуночи.',
        'Eine Schlüsselkarte für ein Konzern-Parkdeck, gültig bis Mitternacht.',
        'Un badge d\'accès à un parking corpo, valable jusqu\'à minuit.',
        '一张公司停车层门禁卡，午夜前有效。',
      ), weight: 2),
      LibraryRow(Tx(
        'A monowire garrote coiled in a wristwatch.',
        'Мономолекулярная удавка, свёрнутая в наручных часах.',
        'Eine Monofaser-Garotte, aufgerollt in einer Armbanduhr.',
        'Un garrot monofilament enroulé dans une montre.',
        '藏在手表里的单分子线绞索。',
      ), weight: 1),
      LibraryRow(Tx(
        'A burner phone with {1d6} missed calls from the same number.',
        'Одноразовый телефон с {1d6} пропущенными с одного номера.',
        'Ein Wegwerfhandy mit {1d6} verpassten Anrufen derselben Nummer.',
        'Un téléphone jetable avec {1d6} appels manqués du même numéro.',
        '一部一次性手机，有{1d6}个来自同一号码的未接来电。',
      ), weight: 2),
      LibraryRow(Tx(
        'Military-grade ICE-breaker software, one use only.',
        'Армейский ледокол для взлома ICE, одноразовый.',
        'ICE-Brecher-Software in Militärqualität, nur einmal nutzbar.',
        'Un brise-glace logiciel de qualité militaire, usage unique.',
        '军用级破冰软件，只能用一次。',
      ), weight: 1),
      LibraryRow(Tx(
        'A real paper photograph of a family nobody recognizes.',
        'Настоящая бумажная фотография семьи, которую никто не знает.',
        'Ein echtes Papierfoto einer Familie, die niemand kennt.',
        'Une vraie photo papier d\'une famille que personne ne reconnaît.',
        '一张真正的纸质照片，上面的一家人谁也不认识。',
      ), weight: 1),
    ],
  ),
  LibraryTable(
    localId: 'complications',
    style: _s,
    folder: LibraryFolder.locale,
    formula: '1d10',
    name: Tx('Street Complications', 'Уличные осложнения',
        'Straßen-Komplikationen', 'Complications urbaines', '街头变数'),
    description: Tx(
      'Something goes sideways during a run.',
      'Что-то идёт не так во время дела.',
      'Etwas läuft während eines Runs schief.',
      'Quelque chose dérape pendant un run.',
      '行动途中出了岔子。',
    ),
    rows: [
      LibraryRow(Tx(
        'The target\'s schedule changed an hour ago.',
        'Расписание цели изменилось час назад.',
        'Der Zeitplan des Ziels hat sich vor einer Stunde geändert.',
        'L\'emploi du temps de la cible a changé il y a une heure.',
        '目标的日程一小时前变了。',
      )),
      LibraryRow(Tx(
        'A citywide blackout: {1d6*10} minutes of darkness and no net.',
        'Блэкаут по всему городу: {1d6*10} минут темноты и без сети.',
        'Stadtweiter Stromausfall: {1d6*10} Minuten Dunkelheit ohne Netz.',
        'Panne géante : {1d6*10} minutes de noir et sans réseau.',
        '全城停电：{1d6*10}分钟的黑暗，网络中断。',
      )),
      LibraryRow(Tx(
        'Someone livestreams the job. Viewers: {1d100*10}.',
        'Кто-то ведёт стрим с места дела. Зрителей: {1d100*10}.',
        'Jemand streamt den Job live. Zuschauer: {1d100*10}.',
        'Quelqu\'un diffuse le boulot en direct. Spectateurs : {1d100*10}.',
        '有人在直播这次行动。观众：{1d100*10}人。',
      )),
      LibraryRow(Tx(
        'The fixer sold the same job to a rival crew.',
        'Фиксер продал ту же работу конкурирующей команде.',
        'Der Fixer hat denselben Job an eine Konkurrenzcrew verkauft.',
        'Le fixer a vendu le même boulot à une équipe rivale.',
        '中间人把同一单活也卖给了另一支队伍。',
      )),
      LibraryRow(Tx(
        'Acid rain eats through cheap gear. Unprotected chrome glitches.',
        'Кислотный дождь разъедает дешёвое снаряжение. Незащищённый хром сбоит.',
        'Säureregen frisst billige Ausrüstung. Ungeschütztes Chrom spinnt.',
        'Une pluie acide ronge le matériel bon marché. Le chrome non protégé bugue.',
        '酸雨腐蚀廉价装备，没有防护的义体开始出错。',
      )),
      LibraryRow(Tx(
        'A bystander recognizes one of you and shouts your {name|old handle|bounty}.',
        'Прохожий узнаёт одного из вас и выкрикивает {имя|старый позывной|сумму награды}.',
        'Ein Passant erkennt jemanden von euch und ruft {den Namen|das alte Handle|das Kopfgeld}.',
        'Un passant reconnaît l\'un de vous et crie {son nom|son ancien pseudo|sa prime}.',
        '有个路人认出你们中的一人，大喊出{名字|旧代号|悬赏金额}。',
      )),
      LibraryRow(Tx(
        'The getaway driver is too high to drive. Their story: [[@quirks]]',
        'Водитель для отхода слишком обдолбан, чтобы вести. Кто он: [[@quirks]]',
        'Der Fluchtfahrer ist zu high zum Fahren. Wer er ist: [[@quirks]]',
        'Le chauffeur est trop défoncé pour conduire. Son profil : [[@quirks]]',
        '负责接应的司机嗨得开不了车。此人：[[@quirks]]',
      )),
      LibraryRow(Tx(
        'Corp security upgrades: {1d4} new drones on patrol.',
        'Корпоративная охрана усилена: {1d4} новых дрона в патруле.',
        'Konzernsicherheit aufgerüstet: {1d4} neue Drohnen auf Patrouille.',
        'Sécurité corpo renforcée : {1d4} nouveaux drones en patrouille.',
        '公司安保升级：新增{1d4}架巡逻无人机。',
      )),
      LibraryRow(Tx(
        'An implant receives a firmware update at the worst moment.',
        'Имплант получает обновление прошивки в самый неподходящий момент.',
        'Ein Implantat zieht im schlechtesten Moment ein Firmware-Update.',
        'Un implant lance une mise à jour au pire moment.',
        '某个植入体在最糟糕的时刻开始更新固件。',
      )),
      LibraryRow(Tx(
        'The package is alive.',
        'Посылка живая.',
        'Das Paket lebt.',
        'Le colis est vivant.',
        '包裹是活的。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'quirks',
    style: _s,
    folder: LibraryFolder.people,
    name: Tx('Street Quirks', 'Уличные причуды', 'Straßen-Marotten',
        'Tics de la rue', '街头怪癖'),
    description: Tx(
      'A detail for fixers, gangers, clerks and other faces in the crowd.',
      'Деталь для фиксеров, бандитов, клерков и прочих лиц в толпе.',
      'Ein Detail für Fixer, Ganger, Angestellte und andere Gesichter in der Menge.',
      'Un détail pour les fixers, gangers, employés et autres visages de la foule.',
      '给中间人、帮派分子、小职员等路人添一个细节。',
    ),
    rows: [
      LibraryRow(Tx(
        'Has a cheap voice modulator that slips into {a cartoon voice|static|an old ad jingle}.',
        'Дешёвый голосовой модулятор иногда срывается в {мультяшный голос|помехи|старый рекламный джингл}.',
        'Ein billiger Stimmmodulator rutscht immer wieder in {eine Comicstimme|Rauschen|einen alten Werbejingle}.',
        'Un modulateur vocal bas de gamme dérape en {voix de dessin animé|grésillements|vieux jingle publicitaire}.',
        '廉价变声器时不时变成{卡通声|杂音|老广告歌}。',
      )),
      LibraryRow(Tx(
        'Wears mirrorshades indoors and never takes them off.',
        'Носит зеркальные очки в помещении и никогда их не снимает.',
        'Trägt drinnen Spiegelbrillen und nimmt sie nie ab.',
        'Porte des lunettes miroir à l\'intérieur et ne les enlève jamais.',
        '室内也戴着反光墨镜，从不摘下。',
      ), weight: 2),
      LibraryRow(Tx(
        'Counts everything out loud, in binary.',
        'Считает всё вслух — в двоичной системе.',
        'Zählt alles laut mit, im Binärsystem.',
        'Compte tout à voix haute, en binaire.',
        '什么都要大声数出来，用二进制。',
      )),
      LibraryRow(Tx(
        'Has a tattoo that animates when they lie.',
        'Татуировка оживает, когда он лжёт.',
        'Hat ein Tattoo, das sich beim Lügen bewegt.',
        'Porte un tatouage qui s\'anime quand il ment.',
        '身上有个撒谎时就会动起来的纹身。',
      )),
      LibraryRow(Tx(
        'Only eats real food and talks about it constantly.',
        'Ест только настоящую еду и постоянно об этом говорит.',
        'Isst nur echtes Essen und redet ständig darüber.',
        'Ne mange que de la vraie nourriture et en parle sans arrêt.',
        '只吃真正的食物，并且老挂在嘴边。',
      ), weight: 2),
      LibraryRow(Tx(
        'Keeps a pet {rat|drone|goldfish in a bag} and names everything after it.',
        'Держит {крысу|дрона|золотую рыбку в пакете} и называет всё в её честь.',
        'Hat {eine Ratte|eine Drohne|einen Goldfisch in einer Tüte} und benennt alles danach.',
        'A {un rat|un drone|un poisson rouge en sachet} et baptise tout d\'après lui.',
        '养着一只{老鼠|无人机|袋装金鱼}，什么都用它的名字命名。',
      )),
      LibraryRow(Tx(
        'Former corp; still says "per my last message".',
        'Бывший корпорат; до сих пор говорит «как я писал ранее».',
        'Ex-Konzerner; sagt immer noch „wie in meiner letzten Nachricht erwähnt“.',
        'Ancien corpo ; dit toujours « comme indiqué dans mon dernier message ».',
        '前公司职员，至今还说“如我上条消息所述”。',
      )),
      LibraryRow(Tx(
        'Chrome hand that twitches toward any weapon in the room.',
        'Хромированная рука дёргается к любому оружию в комнате.',
        'Eine Chromhand, die zu jeder Waffe im Raum zuckt.',
        'Une main de chrome qui tressaille vers chaque arme de la pièce.',
        '一只义手，会不由自主地伸向屋里任何武器。',
      )),
      LibraryRow(Tx(
        'Pays debts in favors, never in eddies.',
        'Возвращает долги услугами, но никогда деньгами.',
        'Zahlt Schulden mit Gefallen, nie mit Eddies.',
        'Règle ses dettes en services, jamais en eddies.',
        '欠债只用人情还，从不给钱。',
      )),
      LibraryRow(Tx(
        'Hums the same pop song, a decade out of date.',
        'Напевает одну и ту же поп-песню десятилетней давности.',
        'Summt denselben Popsong, zehn Jahre aus der Mode.',
        'Fredonne la même chanson pop, démodée depuis dix ans.',
        '总哼着同一首过时十年的流行歌。',
      )),
    ],
  ),
];
