import '../../models/world.dart';
import 'table_library.dart';

const _s = WorldStyle.spaceOpera;

const spaceOperaTables = <LibraryTable>[
  LibraryTable(
    localId: 'port_encounters',
    style: _s,
    folder: LibraryFolder.encounters,
    formula: '1d12',
    name: Tx('Spaceport Encounters', 'Встречи в космопорту',
        'Begegnungen im Raumhafen', 'Rencontres au spatioport', '太空港遭遇'),
    description: Tx(
      'Docking rings, cargo bays and cantinas: who wants something from the crew.',
      'Стыковочные кольца, грузовые отсеки и кантины: кому что-то нужно от экипажа.',
      'Andockringe, Frachtbuchten und Kantinen: wer etwas von der Crew will.',
      'Anneaux d\'amarrage, soutes et cantinas : qui veut quelque chose de l\'équipage.',
      '对接环、货舱和酒馆：谁想从船员身上捞点什么。',
    ),
    rows: [
      LibraryRow(Tx(
        'A customs officer finds an irregularity in your manifest and a price to overlook it: {2d6*100} credits.',
        'Таможенник находит нестыковку в вашем манифесте — и цену, чтобы её не заметить: {2d6*100} кредитов.',
        'Ein Zollbeamter findet eine Unregelmäßigkeit im Manifest — und einen Preis fürs Wegsehen: {2d6*100} Credits.',
        'Un douanier trouve une irrégularité dans votre manifeste, et un prix pour l\'oublier : {2d6*100} crédits.',
        '海关官员在你的货单里发现了问题——以及让他视而不见的价码：{2d6*100}信用点。',
      )),
      LibraryRow(Tx(
        'A stowaway is found in the cargo hold. [[@quirks]]',
        'В грузовом отсеке найден безбилетник. [[@quirks]]',
        'Im Frachtraum wird ein blinder Passagier entdeckt. [[@quirks]]',
        'Un passager clandestin est découvert dans la soute. [[@quirks]]',
        '货舱里发现了一个偷渡者。[[@quirks]]',
      )),
      LibraryRow(Tx(
        'A bounty hunter droid scans each face in the cantina, one by one.',
        'Дроид-охотник за головами сканирует каждое лицо в кантине, одно за другим.',
        'Ein Kopfgeldjäger-Droide scannt in der Kantine jedes Gesicht, eines nach dem anderen.',
        'Un droïde chasseur de primes scanne un à un chaque visage de la cantina.',
        '一个赏金猎人机器人正在酒馆里逐一扫描每张脸。',
      )),
      LibraryRow(Tx(
        'A rival captain challenges you to a race to the jump point. Stakes: {your ship|a cargo|a secret}.',
        'Соперник-капитан вызывает на гонку до точки прыжка. Ставка: {ваш корабль|груз|тайна}.',
        'Ein rivalisierender Kapitän fordert euch zum Rennen zum Sprungpunkt. Einsatz: {euer Schiff|eine Fracht|ein Geheimnis}.',
        'Un capitaine rival vous défie de rallier le point de saut. Enjeu : {votre vaisseau|une cargaison|un secret}.',
        '一位对手船长挑战你们比赛谁先抵达跃迁点。赌注：{你的飞船|一批货物|一个秘密}。',
      )),
      LibraryRow(Tx(
        'A refugee family offers everything they own for passage: [[@salvage]]',
        'Семья беженцев отдаёт всё, что у неё есть, за проезд: [[@salvage]]',
        'Eine Flüchtlingsfamilie bietet alles für eine Überfahrt: [[@salvage]]',
        'Une famille de réfugiés offre tout ce qu\'elle possède pour le passage : [[@salvage]]',
        '一家难民愿拿出全部家当换取搭乘：[[@salvage]]',
      )),
      LibraryRow(Tx(
        'Station security locks down the ring. Nobody leaves for {1d6} hours.',
        'Охрана станции блокирует кольцо. Никто не улетит {1d6} ч.',
        'Die Stationssicherheit riegelt den Ring ab. {1d6} Stunden lang kommt niemand weg.',
        'La sécurité de la station boucle l\'anneau. Personne ne part avant {1d6} heures.',
        '空间站安保封锁了对接环，{1d6}小时内谁也走不了。',
      )),
      LibraryRow(Tx(
        'A mechanic swears your ship is making "the noise". Diagnosis: [[@malfunctions]]',
        'Механик клянётся, что ваш корабль издаёт «тот самый звук». Диагноз: [[@malfunctions]]',
        'Eine Mechanikerin schwört, euer Schiff macht „das Geräusch“. Diagnose: [[@malfunctions]]',
        'Une mécanicienne jure que votre vaisseau fait « le bruit ». Diagnostic : [[@malfunctions]]',
        '一个机械师发誓你的飞船发出了“那种声音”。诊断：[[@malfunctions]]',
      )),
      LibraryRow(Tx(
        'An alien diplomat mistakes the captain for an ambassador and will not be corrected.',
        'Инопланетный дипломат принимает капитана за посла и не желает слушать возражений.',
        'Ein außerirdischer Diplomat hält den Kapitän für einen Botschafter und lässt sich nicht korrigieren.',
        'Un diplomate extraterrestre prend le capitaine pour un ambassadeur et refuse d\'être détrompé.',
        '一位外星外交官把船长错认成大使，怎么解释都没用。',
      )),
      LibraryRow(Tx(
        'Pirates disguised as dock workers are loading the wrong crates onto your ship.',
        'Пираты под видом докеров грузят на ваш корабль не те ящики.',
        'Als Hafenarbeiter verkleidete Piraten laden die falschen Kisten auf euer Schiff.',
        'Des pirates déguisés en dockers chargent les mauvaises caisses dans votre vaisseau.',
        '伪装成码头工人的海盗正把不该装的货箱搬上你的船。',
      )),
      LibraryRow(Tx(
        'A preacher of the void sells star charts that show a planet no one has heard of.',
        'Проповедник пустоты продаёт звёздные карты с планетой, о которой никто не слышал.',
        'Ein Prediger der Leere verkauft Sternkarten mit einem Planeten, den niemand kennt.',
        'Un prêcheur du vide vend des cartes stellaires montrant une planète inconnue de tous.',
        '一个虚空传教士在兜售星图，上面有颗谁也没听过的行星。',
      )),
      LibraryRow(Tx(
        'An old war buddy of the pilot needs a favor, and a fast ship.',
        'Старый армейский друг пилота просит об услуге — и о быстром корабле.',
        'Ein alter Kriegskamerad des Piloten braucht einen Gefallen und ein schnelles Schiff.',
        'Un vieux frère d\'armes du pilote a besoin d\'un service, et d\'un vaisseau rapide.',
        '驾驶员的一位老战友需要帮忙，还需要一艘快船。',
      )),
      LibraryRow(Tx(
        'A crate on the dock is ticking. The label reads "fragile: live specimen".',
        'Ящик на причале тикает. На этикетке: «Хрупкое: живой образец».',
        'Eine Kiste am Dock tickt. Auf dem Etikett steht „Zerbrechlich: lebendes Exemplar“.',
        'Une caisse sur le quai fait tic-tac. L\'étiquette dit « Fragile : spécimen vivant ».',
        '码头上一只箱子在滴答作响，标签写着“易碎：活体样本”。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'comm_rumors',
    style: _s,
    folder: LibraryFolder.rumors,
    formula: '1d10',
    name: Tx('Rumors on the Comm', 'Слухи в эфире', 'Gerüchte im Funk',
        'Rumeurs sur les ondes', '通讯频道传闻'),
    description: Tx(
      'Chatter picked up on open channels between systems.',
      'Болтовня, перехваченная на открытых каналах между системами.',
      'Funkverkehr, aufgeschnappt auf offenen Kanälen zwischen den Systemen.',
      'Des bavardages captés sur les canaux ouverts entre les systèmes.',
      '星系之间公共频道上截获的闲聊。',
    ),
    rows: [
      LibraryRow(Tx(
        'A derelict dreadnought drifts in the asteroid belt, still full of [[@salvage]]',
        'В поясе астероидов дрейфует брошенный дредноут, до сих пор полный добра: [[@salvage]]',
        'Ein verlassenes Schlachtschiff treibt im Asteroidengürtel, noch voller: [[@salvage]]',
        'Un cuirassé abandonné dérive dans la ceinture d\'astéroïdes, encore rempli de : [[@salvage]]',
        '一艘废弃的无畏舰在小行星带漂流，里面还满是：[[@salvage]]',
      )),
      LibraryRow(Tx(
        'The Imperial fleet is massing near {the border|a neutral world|the capital}.',
        'Имперский флот стягивается {к границе|к нейтральному миру|к столице}.',
        'Die imperiale Flotte sammelt sich {an der Grenze|bei einer neutralen Welt|bei der Hauptwelt}.',
        'La flotte impériale se masse {près de la frontière|près d\'un monde neutre|près de la capitale}.',
        '帝国舰队正在{边境|一个中立星球|首都}附近集结。',
      )),
      LibraryRow(Tx(
        'A jump gate went silent. The last message was a child laughing.',
        'Прыжковые врата замолчали. Последним сообщением был детский смех.',
        'Ein Sprungtor ist verstummt. Die letzte Nachricht war Kinderlachen.',
        'Une porte de saut s\'est tue. Le dernier message était un rire d\'enfant.',
        '一座跃迁门失去了联络，最后一条讯息是孩子的笑声。',
      )),
      LibraryRow(Tx(
        'Fuel prices on the frontier just tripled. Someone is hoarding.',
        'Цены на топливо на фронтире только что утроились. Кто-то скупает запасы.',
        'Die Treibstoffpreise an der Grenze haben sich verdreifacht. Jemand hortet.',
        'Le prix du carburant sur la frontière vient de tripler. Quelqu\'un fait des réserves.',
        '边疆的燃料价格刚刚涨了三倍，有人在囤货。',
      )),
      LibraryRow(Tx(
        'A famous smuggler faked their death and is recruiting a new crew.',
        'Знаменитый контрабандист инсценировал свою смерть и набирает новую команду.',
        'Eine berühmte Schmugglerin hat ihren Tod vorgetäuscht und sucht eine neue Crew.',
        'Une célèbre contrebandière a simulé sa mort et recrute un nouvel équipage.',
        '一位著名走私者假死脱身，正在招募新船员。',
      )),
      LibraryRow(Tx(
        'The mining guild pays {1d6*1000} credits for proof of alien ruins on the moon.',
        'Гильдия шахтёров платит {1d6*1000} кредитов за доказательства инопланетных руин на луне.',
        'Die Bergbaugilde zahlt {1d6*1000} Credits für Beweise außerirdischer Ruinen auf dem Mond.',
        'La guilde minière paie {1d6*1000} crédits pour une preuve de ruines extraterrestres sur la lune.',
        '矿业公会出{1d6*1000}信用点，悬赏月球上外星遗迹的证据。',
      )),
      LibraryRow(Tx(
        'A plague ship was turned away from three stations and is still out there.',
        'Чумной корабль развернули на трёх станциях, и он всё ещё где-то там.',
        'Ein Seuchenschiff wurde an drei Stationen abgewiesen und ist noch da draußen.',
        'Un vaisseau pestiféré a été refoulé de trois stations et erre encore.',
        '一艘瘟疫船被三个空间站拒之门外，至今仍在外面游荡。',
      )),
      LibraryRow(Tx(
        'The emperor\'s heir was seen in a dockside bar, dressed as a mechanic.',
        'Наследника императора видели в портовом баре в одежде механика.',
        'Der Thronerbe wurde in einer Hafenbar gesehen, als Mechaniker verkleidet.',
        'L\'héritier de l\'empereur a été vu dans un bar du port, déguisé en mécanicien.',
        '有人在码头酒吧看到了皇位继承人，打扮成一个机械师。',
      )),
      LibraryRow(Tx(
        'A nav beacon is broadcasting coordinates in an old military code.',
        'Навигационный маяк передаёт координаты старым военным шифром.',
        'Eine Navigationsbake sendet Koordinaten in einem alten Militärcode.',
        'Une balise de navigation émet des coordonnées dans un vieux code militaire.',
        '一座导航信标正用旧军用密码广播坐标。',
      )),
      LibraryRow(Tx(
        'Every ship leaving the nebula reports one more crew member than it had.',
        'Каждый корабль, покидающий туманность, сообщает, что экипажа на одного больше.',
        'Jedes Schiff, das den Nebel verlässt, meldet ein Crewmitglied mehr als zuvor.',
        'Chaque vaisseau qui quitte la nébuleuse compte un membre d\'équipage de plus.',
        '每艘离开星云的飞船都报告说船员多了一个。',
      )),
    ],
  ),
  LibraryTable(
    localId: 'salvage',
    style: _s,
    folder: LibraryFolder.loot,
    formula: '1d20',
    name: Tx('Derelict Salvage', 'Трофеи с обломков', 'Wrackbergung',
        'Récupération d\'épave', '残骸打捞'),
    description: Tx(
      'What can be pried from a dead hull, a crashed shuttle or an abandoned outpost.',
      'Что можно выломать из мёртвого корпуса, разбитого челнока или брошенной станции.',
      'Was sich aus toten Rümpfen, abgestürzten Fähren oder verlassenen Außenposten holen lässt.',
      'Ce qu\'on peut arracher à une coque morte, une navette écrasée ou un avant-poste abandonné.',
      '能从报废船体、坠毁的穿梭机或废弃前哨里撬出来的东西。',
    ),
    rows: [
      LibraryRow(Tx(
        '{2d6} crates of military ration bars, mostly edible.',
        '{2d6} ящиков армейских пайков, в основном съедобных.',
        '{2d6} Kisten Militärrationen, größtenteils essbar.',
        '{2d6} caisses de rations militaires, presque toutes comestibles.',
        '{2d6}箱军用口粮，大部分还能吃。',
      ), weight: 4),
      LibraryRow(Tx(
        'A working hyperdrive coil, worth {1d6*500} credits to the right buyer.',
        'Рабочая катушка гипердвигателя: {1d6*500} кредитов у правильного покупателя.',
        'Eine funktionierende Hyperantriebsspule, {1d6*500} Credits wert beim richtigen Käufer.',
        'Une bobine d\'hyperpropulsion en état, {1d6*500} crédits pour le bon acheteur.',
        '一个能用的超空间引擎线圈，找对买家值{1d6*500}信用点。',
      ), weight: 2),
      LibraryRow(Tx(
        'The captain\'s log, encrypted, ending mid-sentence.',
        'Бортовой журнал капитана, зашифрованный и обрывающийся на полуслове.',
        'Das Logbuch des Kapitäns, verschlüsselt, mitten im Satz endend.',
        'Le journal de bord du capitaine, chiffré, s\'interrompant en pleine phrase.',
        '加密的船长日志，在一句话中间戛然而止。',
      ), weight: 2),
      LibraryRow(Tx(
        '{1d4} vacuum suits, one with a {cracked|scorched|bloodstained} visor.',
        '{1d4} скафандра, у одного {треснувший|обожжённый|окровавленный} визор.',
        '{1d4} Raumanzüge, einer mit {gesprungenem|verbranntem|blutbeflecktem} Visier.',
        '{1d4} combinaisons spatiales, dont une à la visière {fêlée|brûlée|tachée de sang}.',
        '{1d4}套真空服，其中一套面罩{裂了|烧焦了|沾着血}。',
      ), weight: 3),
      LibraryRow(Tx(
        'A dormant maintenance droid that wakes up loyal to the first voice it hears.',
        'Спящий ремонтный дроид, который станет верен первому услышанному голосу.',
        'Ein ruhender Wartungsdroide, der der ersten Stimme treu wird, die er hört.',
        'Un droïde de maintenance en veille qui sera fidèle à la première voix entendue.',
        '一台休眠的维修机器人，醒来后会效忠它听到的第一个声音。',
      ), weight: 2),
      LibraryRow(Tx(
        'A cryo pod, still sealed. The occupant\'s name has been scratched off.',
        'Криокапсула, всё ещё запечатанная. Имя пассажира выцарапано.',
        'Eine Kryokapsel, noch versiegelt. Der Name des Insassen wurde weggekratzt.',
        'Un caisson cryogénique encore scellé. Le nom de l\'occupant a été gratté.',
        '一台仍然密封的冷冻舱，舱内人的名字被刮掉了。',
      ), weight: 1),
      LibraryRow(Tx(
        'Plasma rifle power cells, {1d6+1} of them, fully charged.',
        'Энергоячейки для плазменной винтовки, {1d6+1} шт., полностью заряжены.',
        '{1d6+1} voll geladene Energiezellen für Plasmagewehre.',
        '{1d6+1} cellules d\'énergie pour fusil à plasma, pleinement chargées.',
        '{1d6+1}块充满电的等离子步枪能量电池。',
      ), weight: 2),
      LibraryRow(Tx(
        'A crate of alien seeds that pulse faintly in the dark.',
        'Ящик инопланетных семян, слабо пульсирующих в темноте.',
        'Eine Kiste außerirdischer Samen, die im Dunkeln schwach pulsieren.',
        'Une caisse de graines extraterrestres qui pulsent faiblement dans le noir.',
        '一箱在黑暗中微微搏动的外星种子。',
      ), weight: 1),
      LibraryRow(Tx(
        'Navigation data for a shortcut through a forbidden sector.',
        'Навигационные данные о коротком пути через запретный сектор.',
        'Navigationsdaten für eine Abkürzung durch einen verbotenen Sektor.',
        'Des données de navigation pour un raccourci par un secteur interdit.',
        '一份穿越禁区捷径的导航数据。',
      ), weight: 2),
      LibraryRow(Tx(
        'An ornate ceremonial blade from a species believed extinct.',
        'Богато украшенный церемониальный клинок расы, считавшейся вымершей.',
        'Eine prunkvolle Zeremonienklinge eines als ausgestorben geltenden Volkes.',
        'Une lame cérémonielle ornée d\'une espèce qu\'on croyait éteinte.',
        '一把华丽的仪式之刃，出自一个据信已灭绝的种族。',
      ), weight: 1),
    ],
  ),
  LibraryTable(
    localId: 'malfunctions',
    style: _s,
    folder: LibraryFolder.locale,
    formula: '1d10',
    name: Tx('Ship Malfunctions', 'Неполадки корабля', 'Schiffsdefekte',
        'Avaries du vaisseau', '飞船故障'),
    description: Tx(
      'Something breaks at the worst possible moment.',
      'Что-то ломается в самый неподходящий момент.',
      'Etwas geht im ungünstigsten Moment kaputt.',
      'Quelque chose casse au pire moment.',
      '总在最要命的时候坏掉的东西。',
    ),
    rows: [
      LibraryRow(Tx(
        'Artificial gravity flickers: {1d6} minutes of weightlessness at random.',
        'Искусственная гравитация мигает: {1d6} минут невесомости в случайный момент.',
        'Die künstliche Schwerkraft flackert: {1d6} Minuten Schwerelosigkeit zu zufälligen Zeiten.',
        'La gravité artificielle vacille : {1d6} minutes d\'apesanteur au hasard.',
        '人工重力时断时续：随机出现{1d6}分钟失重。',
      )),
      LibraryRow(Tx(
        'A coolant leak fills the engine room with freezing fog.',
        'Утечка хладагента наполняет машинное отделение ледяным туманом.',
        'Ein Kühlmittelleck füllt den Maschinenraum mit eisigem Nebel.',
        'Une fuite de liquide de refroidissement remplit la salle des machines d\'un brouillard glacial.',
        '冷却剂泄漏，引擎室充满冰冷的雾气。',
      )),
      LibraryRow(Tx(
        'The ship\'s AI starts answering in {rhyme|a dead language|the captain\'s voice}.',
        'ИИ корабля начинает отвечать {в рифму|на мёртвом языке|голосом капитана}.',
        'Die Schiffs-KI antwortet plötzlich {in Reimen|in einer toten Sprache|mit der Stimme des Kapitäns}.',
        'L\'IA du vaisseau se met à répondre {en rimes|dans une langue morte|avec la voix du capitaine}.',
        '飞船AI开始{用押韵|用一门死语言|用船长的声音}回答问题。',
      )),
      LibraryRow(Tx(
        'Life support drops to {2d6*5}% efficiency. Tempers and oxygen both run short.',
        'Система жизнеобеспечения падает до {2d6*5}%. Кончаются и кислород, и терпение.',
        'Die Lebenserhaltung fällt auf {2d6*5} % Leistung. Sauerstoff und Geduld werden knapp.',
        'Le support vital tombe à {2d6*5} % d\'efficacité. L\'oxygène et la patience s\'épuisent.',
        '生命维持系统效率降到{2d6*5}%，氧气和耐心都快耗尽了。',
      )),
      LibraryRow(Tx(
        'A hull breach alarm, but no breach anyone can find.',
        'Сигнал разгерметизации корпуса — но пробоину никто не находит.',
        'Hüllenbruch-Alarm, aber niemand findet ein Leck.',
        'Alarme de brèche dans la coque, mais personne ne trouve la brèche.',
        '船体破损警报响了，却谁也找不到破口。',
      )),
      LibraryRow(Tx(
        'The hyperdrive misjumps and drops you {1d6} light-years off course.',
        'Гипердвигатель ошибается при прыжке и выбрасывает вас на {1d6} св. лет с курса.',
        'Der Hyperantrieb verspringt sich und wirft euch {1d6} Lichtjahre vom Kurs ab.',
        'L\'hyperpropulseur rate son saut et vous dépose à {1d6} années-lumière du cap.',
        '超空间引擎跃迁失误，把你们甩出航线{1d6}光年。',
      )),
      LibraryRow(Tx(
        'The airlock cycles on its own, twice, at 03:00 ship time.',
        'Шлюз сам срабатывает — дважды, в 03:00 по корабельному времени.',
        'Die Luftschleuse durchläuft von selbst zwei Zyklen, um 03:00 Bordzeit.',
        'Le sas se déclenche seul, deux fois, à 3 h, heure du bord.',
        '船上时间凌晨三点，气闸自己循环了两次。',
      )),
      LibraryRow(Tx(
        'Weapons power routes into the galley. The coffee machine is now dangerous.',
        'Питание орудий уходит на камбуз. Кофемашина теперь опасна.',
        'Die Waffenenergie fließt in die Kombüse. Die Kaffeemaschine ist jetzt gefährlich.',
        'L\'énergie des armes est déviée vers la cuisine. La machine à café est désormais dangereuse.',
        '武器能源被导入了厨房，咖啡机现在很危险。',
      )),
      LibraryRow(Tx(
        'Sensors show a second ship matching your every move.',
        'Сенсоры показывают второй корабль, повторяющий каждое ваше движение.',
        'Die Sensoren zeigen ein zweites Schiff, das jede eurer Bewegungen spiegelt.',
        'Les capteurs montrent un second vaisseau qui imite chacun de vos mouvements.',
        '传感器显示有另一艘船在复刻你们的每个动作。',
      )),
      LibraryRow(Tx(
        'A repair bot goes rogue and starts "improving" the ship. Its handler: [[@quirks]]',
        'Ремонтный бот выходит из-под контроля и начинает «улучшать» корабль. Его оператор: [[@quirks]]',
        'Ein Reparaturbot dreht durch und „verbessert“ das Schiff. Seine Betreuerin: [[@quirks]]',
        'Un robot de réparation devient incontrôlable et « améliore » le vaisseau. Son opérateur : [[@quirks]]',
        '一台维修机器人失控，开始“改良”飞船。它的操作员：[[@quirks]]',
      )),
    ],
  ),
  LibraryTable(
    localId: 'quirks',
    style: _s,
    folder: LibraryFolder.people,
    name: Tx('Crew Quirks', 'Причуды экипажа', 'Crew-Marotten',
        'Manies d\'équipage', '船员怪癖'),
    description: Tx(
      'Habits of spacers, officers, aliens and dockhands.',
      'Привычки космолётчиков, офицеров, инопланетян и докеров.',
      'Eigenheiten von Raumfahrern, Offizieren, Aliens und Dockarbeitern.',
      'Habitudes de spatiaux, d\'officiers, d\'extraterrestres et de dockers.',
      '太空人、军官、外星人和码头工的小习惯。',
    ),
    rows: [
      LibraryRow(Tx(
        'Talks to the ship as if it were an old friend.',
        'Разговаривает с кораблём, как со старым другом.',
        'Redet mit dem Schiff wie mit einem alten Freund.',
        'Parle au vaisseau comme à un vieil ami.',
        '跟飞船说话像跟老朋友聊天一样。',
      ), weight: 2),
      LibraryRow(Tx(
        'Never removes their {helmet|gloves|medal}, even to sleep.',
        'Никогда не снимает {шлем|перчатки|медаль}, даже во сне.',
        'Legt {den Helm|die Handschuhe|den Orden} nie ab, nicht einmal zum Schlafen.',
        'Ne retire jamais {son casque|ses gants|sa médaille}, même pour dormir.',
        '从不摘下{头盔|手套|勋章}，睡觉也不摘。',
      )),
      LibraryRow(Tx(
        'Superstitious about the number {three|seven|thirteen}.',
        'Суеверно боится числа {три|семь|тринадцать}.',
        'Abergläubisch, was die Zahl {drei|sieben|dreizehn} angeht.',
        'Superstitieux au sujet du nombre {trois|sept|treize}.',
        '对数字{三|七|十三}非常迷信。',
      )),
      LibraryRow(Tx(
        'Grew up on a low-gravity moon and stoops in every doorway.',
        'Вырос на луне с низкой гравитацией и пригибается в каждом проёме.',
        'Wuchs auf einem Mond mit geringer Schwerkraft auf und bückt sich in jeder Tür.',
        'A grandi sur une lune à faible gravité et se baisse à chaque porte.',
        '在低重力卫星上长大，过每道门都要弯腰。',
      )),
      LibraryRow(Tx(
        'Keeps a jar of soil from their homeworld and sniffs it when sad.',
        'Хранит банку земли с родной планеты и нюхает её, когда грустно.',
        'Hat ein Glas Erde von der Heimatwelt und riecht daran, wenn er traurig ist.',
        'Garde un bocal de terre de son monde natal et le renifle quand il est triste.',
        '随身带着一罐故乡的泥土，难过时就闻一闻。',
      )),
      LibraryRow(Tx(
        'Translates alien idioms literally, with confidence.',
        'Переводит инопланетные идиомы дословно — и уверенно.',
        'Übersetzt außerirdische Redewendungen wörtlich, mit voller Überzeugung.',
        'Traduit les expressions extraterrestres au pied de la lettre, avec aplomb.',
        '信心满满地把外星俗语逐字直译。',
      ), weight: 2),
      LibraryRow(Tx(
        'Salutes everyone, including droids.',
        'Отдаёт честь всем, включая дроидов.',
        'Salutiert vor allen, auch vor Droiden.',
        'Salue tout le monde, droïdes compris.',
        '对谁都敬礼，包括机器人。',
      )),
      LibraryRow(Tx(
        'Has been in cryosleep so long their slang is a century old.',
        'Так долго пробыл в криосне, что его сленгу сто лет.',
        'Lag so lange im Kryoschlaf, dass sein Slang ein Jahrhundert alt ist.',
        'A dormi si longtemps en cryo que son argot a un siècle de retard.',
        '冷冻休眠太久，说的俚语已经过时一百年。',
      )),
      LibraryRow(Tx(
        'Hums the anthem of a republic that no longer exists.',
        'Напевает гимн республики, которой больше нет.',
        'Summt die Hymne einer Republik, die es nicht mehr gibt.',
        'Fredonne l\'hymne d\'une république qui n\'existe plus.',
        '总哼着一个早已不复存在的共和国的国歌。',
      )),
      LibraryRow(Tx(
        'Bets on everything, pays in ration chits.',
        'Спорит на что угодно и расплачивается талонами на паёк.',
        'Wettet auf alles und zahlt mit Rationsmarken.',
        'Parie sur tout et paie en tickets de rationnement.',
        '什么都要打赌，输了就用口粮券付账。',
      )),
    ],
  ),
];
